/* =====================================================================
 *  客户数据 —— 由 tools/xlsx_to_data.py 从真实导入表自动生成
 *  共 1440 个可定位客户（有国家信息）。
 *  另有 1777 个客户因缺少国家信息未能上图（其中欠款合计 €217,813.64）。
 *  ⚠ 本表无“最后联系/下单日期”，所以“久未联系”视角暂无数据。
 *     要点亮该视角，请提供带日期的导出，再重跑本脚本即可。
 * ===================================================================== */

const META = { unplaced: 1777, unplacedDebt: 217813.64 };

const CUSTOMERS = [
  {"company":"LONG DA MODA GMBH LD FASHION","country":"DE","city":"Neuss","lat":51.198,"lng":6.6917,"debt":160.0},
  {"company":"Flora 巴塞罗那","country":"ES","city":"Barcelona","lat":41.3851,"lng":2.1734,"debt":2494.5,"sales":"Livio"},
  {"company":"SC ADIGHERIN SRL","country":"RO","sales":"Veronica"},
  {"company":"georgios gogoletsios","country":"GR","city":"Larisa"},
  {"company":"Yani Rusev","country":"BG"},
  {"company":"VICTOR","country":"RO"},
  {"company":"avi","country":"FR"},
  {"company":"ML S.R.L.S","country":"IT","city":"CALTANISSETTA","sales":"Veronica"},
  {"company":"cathy","country":"FR"},
  {"company":"KATARINA,obrt za trgovinu,vl. Mladen J","country":"HR","city":"SPLIT","lat":43.5081,"lng":16.4402,"debt":645.0,"sales":"Livio"},
  {"company":"AJM SRL A SOCIO UNICO","country":"IT","city":"FUNO DI ARGELATO","lat":44.6333,"lng":11.35,"region":"Emilia-Romagna"},
  {"company":"朱海慧 PINGTOUGE sarzana ABC","country":"IT","city":"SARZANA","sales":"Livio"},
  {"company":"CO.GI.DISTRIBUZIONE DI CALVANESE DAMIANO COSIMO","country":"IT","city":"CAMPOLI DEL MONTE TABURNO","sales":"Vito"},
  {"company":"MONZA 允浪","country":"IT","city":"Milano","lat":45.4642,"lng":9.19,"region":"Lombardia","debt":5914.0},
  {"company":"A.M.J SRL","country":"IT","debt":380.8,"sales":"Veronica"},
  {"company":"MORENA SPAIN SINGLE MEMBER PC","country":"GR","city":"PATRA","lat":38.2466,"lng":21.7346,"debt":8280.0},
  {"company":"GY FASHION IKE","country":"GR","city":"ATHENS","lat":37.9838,"lng":23.7275,"debt":-1552.0},
  {"company":"borse e accessori 蔡秀莲","country":"IT","city":"civitanova","lat":43.3074,"lng":13.7281,"region":"Marche","debt":18854.5,"sales":"Nico"},
  {"company":"LA GRUCCIA","country":"IT","sales":"Veronica"},
  {"company":"MIA S.R.L","country":"IT","sales":"Veronica"},
  {"company":"EBLA PARTNERS SRL","country":"RO","city":"BUCURESTI, SECTOR 6","debt":1980.0},
  {"company":"PELLETERIA LINDA DI ZHANG LI FANG","country":"IT","city":"TORINO","lat":45.0703,"lng":7.6869,"region":"Piemonte","debt":411.0},
  {"company":"Giusy Contaldo","country":"IT"},
  {"company":"Amaniel","country":"ES","city":"Sesena"},
  {"company":"bajro","country":"CZ","city":"karlovy vary","debt":1273.05},
  {"company":"Vania Jakob","country":"AT"},
  {"company":"Giovanna perazzo","country":"IT"},
  {"company":"DI M. KH. CHEIKH MARAI","country":"IT","sales":"Veronica"},
  {"company":"sandra fischer","country":"DE"},
  {"company":"LE COIN D'ALSACE SARL","country":"FR","sales":"Veronica"},
  {"company":"- 张建MbGb.PT 顺","country":"PT","city":"VILLA DO CONTE"},
  {"company":"SAS CHIC WOMEN","country":"FR","sales":"Veronica"},
  {"company":"陈雷 THE STAR SRL","country":"IT","city":"roma","lat":41.9028,"lng":12.4964,"region":"Lazio"},
  {"company":"VTON ROGERS BIJOUX","country":"AI","sales":"Veronica"},
  {"company":"Di Invernizzi luca &c","country":"IT","city":"bresso"},
  {"company":"MOVROZ EE","country":"GR","sales":"Veronica"},
  {"company":"SARL LAURA","country":"FR","sales":"Livio"},
  {"company":"kim de leij","country":"NL"},
  {"company":"Simon","country":"DE"},
  {"company":"Karine Jalicot","country":"FR"},
  {"company":"isabella cazzola","country":"IT"},
  {"company":"Marco Marri","country":"IT"},
  {"company":"cheniki","country":"FR"},
  {"company":"noelia aguila calzado","country":"ES"},
  {"company":"simona ricci","country":"IT"},
  {"company":"Jennifer Jelinek","country":"DE"},
  {"company":"Yelda Zeybek","country":"DE"},
  {"company":"Nina Leahey","country":"CY"},
  {"company":"SARL SO & LO 叶宁","country":"FR","city":"AUBERVILLIERS","lat":48.9131,"lng":2.3835},
  {"company":"- Ashley.SP 安","country":"ES","city":"BADALONA","lat":41.45,"lng":2.2475,"debt":995.0,"sales":"Livio"},
  {"company":"NICHEN MAISON DI ZONTA PAOLO","country":"IT","sales":"Veronica"},
  {"company":"DIS MOI BOUTIQUE DI BOI MAURIZIO","country":"IT","sales":"Veronica"},
  {"company":"PASI ALESSANDRO LE AGAVI PREZIOSITÀ E ARTICOLI DA REGALO","country":"IT","sales":"Veronica"},
  {"company":"Papaya Mode GMBH","country":"DE","city":"Neuss","lat":51.198,"lng":6.6917,"debt":6095.0},
  {"company":"LOWIN 怡高 YouKu.F.on","country":"ES","city":"BADALONA","lat":41.45,"lng":2.2475,"sales":"Livio"},
  {"company":"TE-JO","country":"DE","sales":"Veronica"},
  {"company":"sarah","country":"BE"},
  {"company":"caroline van espen","country":"BE"},
  {"company":"Ena franca","country":"IT"},
  {"company":"Nesi Simone","country":"IT"},
  {"company":"Gian Elia Amoretti","country":"IT"},
  {"company":"Arianna Bongi","country":"IT"},
  {"company":"Volkova Oleksandra","country":"IT"},
  {"company":"Daniela Longo","country":"IT"},
  {"company":"Nadine Dallmann","country":"DE"},
  {"company":"Heike Lange","country":"DE"},
  {"company":"jaja","country":"FR"},
  {"company":"Fischer Markus","country":"DE"},
  {"company":"FINDU COLLECTION","country":"ES","city":"MADRID","lat":40.4168,"lng":-3.7038,"debt":1959.6},
  {"company":"国意New look bags di Stefano","country":"IT","city":"BARI","lat":41.1171,"lng":16.8719,"region":"Puglia","debt":2805.0,"sales":"Veronica"},
  {"company":"papaya 大女婿 maryco yu gian ly","country":"DE","sales":"Veronica"},
  {"company":"Monica Popa","country":"RO"},
  {"company":"Stefania MM SAS","country":"IT","city":"CITTA' SANT'ANGELO","debt":1770.0,"sales":"Livio"},
  {"company":"MINI NANA","country":"FR","city":"Marseille","lat":43.2965,"lng":5.3698,"debt":432.0},
  {"company":"PELLEMANIA SRL","country":"IT","sales":"Veronica"},
  {"company":"MEEA S.R.L","country":"IT","sales":"Veronica"},
  {"company":"CELIAN & BAGS S.L","country":"ES","sales":"Veronica"},
  {"company":"大众箱包","country":"ES","city":"Badalona","lat":41.45,"lng":2.2475,"debt":634.0},
  {"company":"LICA MODA 比利时夏天.四通","country":"BE","city":"ANDERLECHT","debt":520.0},
  {"company":"FRITSCH FASHION GMBH","country":"AT","sales":"Veronica"},
  {"company":"TIGO S.R.L","country":"IT","city":"RAGUSA","sales":"Veronica"},
  {"company":"le kiwi Modevertriebs gmbh","country":"DE","city":"neuss","lat":51.198,"lng":6.6917},
  {"company":"SAS JAJA FABRICANT GROSSISTE","country":"FR","sales":"Veronica"},
  {"company":"PAN GMBH","country":"AT","city":"BERGLIEIM"},
  {"company":"PUNTO STOCK DI ARBULLA ATTILIO & C. S.A.S.","country":"IT","sales":"Veronica"},
  {"company":"M.CONVERTINI E.K","country":"DE","sales":"Veronica"},
  {"company":"Leonard Group Srl new har","country":"IT","city":"TORINO","lat":45.0703,"lng":7.6869,"region":"Piemonte","sales":"Livio"},
  {"company":"THREE DIAMONDS D.O.O","country":"HR","debt":459.5,"sales":"Veronica"},
  {"company":"boutique","country":"BE"},
  {"company":"CRYSOCHOOU ELEFTHERIOS","country":"GR","sales":"Veronica"},
  {"company":"AGGELI ANNA","country":"GR","sales":"Veronica"},
  {"company":"COM MIXT SILV DAN S.R.L","country":"RO","sales":"Veronica"},
  {"company":"GEA PARGAS M.IKE","country":"GR","sales":"Veronica"},
  {"company":"TSIGRI AIKATERINI 散客","country":"GR","city":"ΜΕΓΑΡΑ"},
  {"company":"M BOUTABOUCHE AMINE","country":"FR","sales":"Veronica"},
  {"company":"SYLVIA SEIDL","country":"AT","sales":"Veronica"},
  {"company":"瑞城 BADALONA 箱 安/四","country":"ES","sales":"Livio"},
  {"company":"WIG S.C. PAWEL WYGAS","country":"PL","sales":"Veronica"},
  {"company":"ANGEL GROUP C21","country":"IT","debt":750.0,"sales":"Livio"},
  {"company":"RAFA Giromoda bends西/安","country":"ES","city":"TORROELLA DE MONTGRI","sales":"Livio"},
  {"company":"Luigi Mickel","country":"DE","city":"Neuss","lat":51.198,"lng":6.6917},
  {"company":"L3 LIVE IN STYLE GMBH","country":"DE","city":"BAD KISSIGEN-GERMANY"},
  {"company":"CONVIDADISSIMA","country":"PT"},
  {"company":"良勇","country":"IT","city":"PISA","sales":"Livio"},
  {"company":"radka Petkova","country":"BG"},
  {"company":"DJUDI 2012 EOOD 散","country":"BG","city":"Elin Pelin","sales":"Livio"},
  {"company":"COX FASHION 德国.安","country":"DE","sales":"Livio"},
  {"company":"Baier","country":"DE"},
  {"company":"HosenshopGmbt","country":"DE","sales":"Livio"},
  {"company":"LORETTA BAGS LTD","country":"BG","city":"Nesebar Bulgaria","sales":"Nico"},
  {"company":"Sultani","country":"DE"},
  {"company":"SRL H&S GROUP","country":"BE","sales":"Livio"},
  {"company":"LOOK UP","country":"CS","city":"Belgreid"},
  {"company":"Elisa Manzo","country":"IT"},
  {"company":"DIGIACOMI FRANCESCA","country":"FR"},
  {"company":"ZHON HUA","country":"GR","city":"THESSALONIKH - GRECE","debt":-1835.0},
  {"company":"PAN LEDERWAREN-U TEXTIL GROSSHANDEL GMBH","country":"DE","city":"MUNCHEN","lat":48.1351,"lng":11.582,"debt":2355.0},
  {"company":"FOREST S.L.","country":"ES","city":"MADRID","lat":40.4168,"lng":-3.7038,"debt":645.0,"sales":"Veronica"},
  {"company":"SEBASTIANA","country":"IT","city":"TORTONA","lat":44.8943,"lng":8.8643,"region":"Piemonte"},
  {"company":"Bv Xanten","country":"BE","sales":"Veronica"},
  {"company":"Andreas' shop","country":"ME"},
  {"company":"MORGANTI FRANCA","country":"IT","city":"CASTAGNETO CARDUCCI","sales":"Vito"},
  {"company":"SHOP AND CO LTD","country":"GR","city":"GLYKA NERA - GRECIA","debt":2741.0},
  {"company":"NVL S.R.L","country":"IT","sales":"Veronica"},
  {"company":"BOUTIQUE MALL","country":"RO","city":"BUCURESTI, SECTOR 2","sales":"Veronica"},
  {"company":"Dautel Eva","country":"ES"},
  {"company":"NAISCA - FTL CONSEIL P175","country":"FR","city":"GEMENOS"},
  {"company":"BINDA MONICA","country":"IT","sales":"Veronica"},
  {"company":"Michela Magrini","country":"IT"},
  {"company":"MME VALENTIN KARINE","country":"FR","sales":"Veronica"},
  {"company":"diego maggetto","country":"IT","city":"Verbania","lat":45.9217,"lng":8.5519,"region":"Piemonte"},
  {"company":"DLF KAROL DZIUBEK","country":"PL"},
  {"company":"KRYSTIAN KANCOK","country":"PL","sales":"Veronica"},
  {"company":"M ora ind LTD","country":"BG","sales":"Livio"},
  {"company":"NAIF S.R.L","country":"IT","city":"CATANIA","lat":37.5079,"lng":15.083,"region":"Sicilia","sales":"Veronica"},
  {"company":"KRISTI STIL 2018 EOOD","country":"BG","sales":"Veronica"},
  {"company":"Kristi","country":"BG"},
  {"company":"Musterzimmer 刷 自提","country":"AT","city":"Turnau","sales":"Livio"},
  {"company":"ADAMANTIO DI ERIKA GASSANNI","country":"IT","sales":"Veronica"},
  {"company":"Shimo Studio","country":"FR","city":"PARIS 2","sales":"Livio"},
  {"company":"Daniela q","country":"IT","city":"CATANIA","lat":37.5079,"lng":15.083,"region":"Sicilia"},
  {"company":"COMEUROTEX","country":"BE","sales":"Veronica"},
  {"company":"- JustLili蕾.DE 安/四","country":"DE","sales":"Livio"},
  {"company":"GIUSEPPE ERCOLANO","country":"IT","city":"rapallo"},
  {"company":"CARRERA COLLECTION","country":"RO","sales":"Veronica"},
  {"company":"BV THIS IS FASHION","country":"BE","sales":"Veronica"},
  {"company":"ST.PIPERAKIS-CHR.DELINIKOLAS GP","country":"GR","sales":"Veronica"},
  {"company":"MAJIN BU LDT","country":"GB","sales":"Veronica"},
  {"company":"MO.G.SRL","country":"IT","city":"PESCARA","sales":"Veronica"},
  {"company":"Kastell Snc di Castelli Davide e Flavia","country":"IT","city":"SAN LAZZARO DI SAVENA","lat":44.4716,"lng":11.41,"region":"Emilia-Romagna","sales":"Veronica"},
  {"company":"ST.PAPAIOANNOU.Sa","country":"GR","sales":"Livio"},
  {"company":"Algros d.o.o. Antonio","country":"HR","city":"Zagreb","lat":45.815,"lng":15.9819,"sales":"Nico"},
  {"company":"laafissi","country":"GB"},
  {"company":"New harlem","country":"IT","city":"TORINO","lat":45.0703,"lng":7.6869,"region":"Piemonte","sales":"Livio"},
  {"company":"PAPAGIANNIS","country":"GR"},
  {"company":"TOTI DI DONATI MONICA E SIMONA S.N.C.","country":"IT","city":"VIAREGGIO","lat":43.8664,"lng":10.2503,"region":"Toscana","sales":"Vito"},
  {"company":"CLOT S.R.L","country":"IT","city":"CATANIA","lat":37.5079,"lng":15.083,"region":"Sicilia","sales":"Vito"},
  {"company":"GREGORIO GRZEGORZ ZONTEK","country":"PL","city":"jaworze"},
  {"company":"-","country":"IT"},
  {"company":"ALANDA wu xiaofeng","country":"DE","sales":"Livio"},
  {"company":"MIA DI CAMPAGNARO ANGELA","country":"IT","sales":"Veronica"},
  {"company":"PedrosFashion","country":"CZ","city":"Praha - Dejvice","sales":"Livio"},
  {"company":"I SEDE LEGALE ALBA PARAZZINI SL","country":"ES","sales":"Veronica"},
  {"company":"Ica Macarie","country":"RO"},
  {"company":"Irene Donata Bramato","country":"IT"},
  {"company":"1Anastasia","country":"FR"},
  {"company":"Filipe Janelas","country":"PT"},
  {"company":"Daire","country":"FR"},
  {"company":"lili","country":"FR"},
  {"company":"Izabela Kolar","country":"HR"},
  {"company":"CHICMILANO","country":"IT"},
  {"company":"Hilda Agopian","country":"NL"},
  {"company":"iseli susanne","country":"AT"},
  {"company":"Manuel Mohorich","country":"BE"},
  {"company":"Agata Blink","country":"PL"},
  {"company":"Marlena","country":"PL"},
  {"company":"Elizabeta","country":"HR"},
  {"company":"christian ruhs","country":"AT"},
  {"company":"Ciulacu trifu","country":"RO"},
  {"company":"Marianna Nika","country":"GR"},
  {"company":"新万豪","country":"GR","sales":"Veronica"},
  {"company":"SUGAR BLUES SRL","country":"IT","city":"Parma"},
  {"company":"SURJEET HANDICRAFT.GMBH","country":"DE","city":"MUNCHEN","lat":48.1351,"lng":11.582},
  {"company":"NALA PRALA BV-alpini","country":"BE","city":"Sint-Truiden","sales":"Livio"},
  {"company":"naomi gautieri","country":"IT"},
  {"company":"Lies Vanhoedenaghe","country":"BE"},
  {"company":"LA FELICE S.R.L.S","country":"IT","city":"PONTASSIEVE","sales":"Veronica"},
  {"company":"CHRISTIAN RUHS GMBH","country":"AT","sales":"Veronica"},
  {"company":"Mohsine El haimer","country":"IT"},
  {"company":"mhamedbara97@gmail.com","country":"IT"},
  {"company":"elita","country":"IT"},
  {"company":"Idrisova","country":"AT"},
  {"company":"BAGEEE GMBH","country":"DE","city":"ESCHBORN-DREIEICH"},
  {"company":"ADRIANA BIJOUX，LLC","country":"US","city":"MIAMI","sales":"Vito"},
  {"company":"JUNDA Inh. JUN ZHANG","country":"DE","city":"HAMBURG","lat":53.5511,"lng":9.9937},
  {"company":"- LCL.SYSTYLE.FR 安","country":"FR","sales":"Livio"},
  {"company":"Galerie de beaute","country":"GR","city":"Maroussi"},
  {"company":"MELLE D. SAS DOUBLED","country":"FR","sales":"Veronica"},
  {"company":"catarina 1","country":"PT"},
  {"company":"DE FILIPPO MONICA","country":"IT","sales":"Veronica"},
  {"company":"DUEDUE S.R.L","country":"IT","sales":"Veronica"},
  {"company":"克章","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia"},
  {"company":"STIGIOS FORTE DEI MARMI DI STAGETTI ENRICO","country":"IT","sales":"Veronica"},
  {"company":"PELLETTERIA CALIN","country":"IT","sales":"Veronica"},
  {"company":"republica S.R.L","country":"IT","city":"PRATO","lat":43.8777,"lng":11.0955,"region":"Toscana","debt":328.5,"sales":"Vito"},
  {"company":"PAN GMBH 比利时","country":"AT","city":"BERGHEIM","sales":"Vito"},
  {"company":"Francesco Stefanelli 1","country":"ES"},
  {"company":"FRANCESCO STEFANELLI","country":"ES","sales":"Veronica"},
  {"company":"KASTELL SNC","country":"IT","city":"SAN LAZZARO DI SAVENA","lat":44.4716,"lng":11.41,"region":"Emilia-Romagna","sales":"Veronica"},
  {"company":"ANTONELLA MEROLA","country":"IT"},
  {"company":"Sabato Alfieri","country":"IT"},
  {"company":"Joanna Chojnacka","country":"PL"},
  {"company":"Antonio Melro","country":"PT"},
  {"company":"Nicole Krambeck","country":"DE"},
  {"company":"Rosi Zedda","country":"IT"},
  {"company":"TRAGAKI MARIA","country":"GR"},
  {"company":"SARL DISTRIBUTION CARNABY","country":"FR","city":"Thonon les Bains","sales":"Veronica"},
  {"company":"KONRAD WERNER RAUMAUSSTATTUNG","country":"DE","sales":"Veronica"},
  {"company":"AILIA GMBH","country":"DE","city":"NEUSS","lat":51.198,"lng":6.6917},
  {"company":"orpel","country":"FR"},
  {"company":"ALTA MODA DI ZYANE RACHIDA","country":"IT","city":"VERGATO","sales":"Veronica"},
  {"company":"Luca Giacobbe","country":"IT"},
  {"company":"ANNA","country":"CH","city":"NYON","sales":"Livio"},
  {"company":"Lucia Angelillo","country":"IT","city":"Nola"},
  {"company":"MOSTWANTED ACCESORIES SL","country":"ES","sales":"Veronica"},
  {"company":"Damyrak Taraachy","country":"IT"},
  {"company":"1oscar","country":"ES"},
  {"company":"MELNICAKOVA ANNA","country":"SK","sales":"Veronica"},
  {"company":"Bags4you","country":"PL"},
  {"company":"Постыляков Сергей Сергеевич","country":"RU"},
  {"company":"olandlaura","country":"NL"},
  {"company":"Ciro Nazzaro","country":"IT"},
  {"company":"DE SOFI-EOOD","country":"BG","city":"SOFIA BULGARIA"},
  {"company":"LA CLER S.R.L.S. A UNICO SOCIO","country":"IT","city":"CALABRIA","sales":"Veronica"},
  {"company":"PICCOLA AZZU DI BALLOCCHI LARA","country":"IT","city":"BOLANO","sales":"Veronica"},
  {"company":"inside technologies srl","country":"RO","city":"CRAIOVA","sales":"Vito"},
  {"company":"绍敢","country":"IT","city":"PALERMO","lat":38.1157,"lng":13.3613,"region":"Sicilia","sales":"Veronica"},
  {"company":"Schmitt","country":"FR"},
  {"company":"Catello imparato","country":"IT"},
  {"company":"Bożena Zakrzewska","country":"PL"},
  {"company":"Sklep odzieżowy fashion alina Pływaczyk","country":"PL"},
  {"company":"Nagham Ramia Saoud","country":"LB"},
  {"company":"Ralitza Baeva","country":"BG"},
  {"company":"GUILLAUX","country":"FR"},
  {"company":"Isokorpi Merja","country":"FI"},
  {"company":"omar","country":"LY"},
  {"company":"Janina Roszkowska","country":"PL"},
  {"company":"Tatjana Sevostjanova","country":"LV"},
  {"company":"giada evangelista","country":"IT"},
  {"company":"Silvia/Rossanda","country":"IT"},
  {"company":"Kotni Bahija","country":"FR"},
  {"company":"AIRE","country":"IT"},
  {"company":"Samantha","country":"IT"},
  {"company":"fiorella","country":"IT"},
  {"company":"Dragomir Iulia","country":"RO"},
  {"company":"ginnysrls","country":"IT"},
  {"company":"Sara Rondelli","country":"IT"},
  {"company":"Chloé Devedeleer","country":"BE"},
  {"company":"Sadia Akter","country":"IT"},
  {"company":"LOLITA","country":"IT"},
  {"company":"Jeniver saade","country":"LB"},
  {"company":"Serge Van Der Poorten","country":"BE"},
  {"company":"Enrico Andreano","country":"IT"},
  {"company":"Huang Ketiao","country":"IT"},
  {"company":"Eirini Tsakiri","country":"GR"},
  {"company":"Hausfelder h.tondera gmbh","country":"DE","city":"Dortmund","sales":"Nico"},
  {"company":"CALIFFI DARIA","country":"IT","city":"VERBANIA","lat":45.9217,"lng":8.5519,"region":"Piemonte","sales":"Veronica"},
  {"company":"MB BITES NAMAI","country":"LT","sales":"Veronica"},
  {"company":"Kess","country":"CH"},
  {"company":"GIO FASHION DI PICAZIO GIOVANNA","country":"IT","sales":"Veronica"},
  {"company":"TEKSTILPROMET D.D.","country":"HR","city":"Zagreb","lat":45.815,"lng":15.9819},
  {"company":"Antonio Spagnolo","country":"IT"},
  {"company":"Steffen Mösche","country":"DE"},
  {"company":"Vangeliya Kitanova","country":"BG"},
  {"company":"Carlotta Trupia","country":"IT"},
  {"company":"Lara Winter","country":"DE"},
  {"company":"antonella malara","country":"IT"},
  {"company":"Ladislav Kadar","country":"SK"},
  {"company":"chiara fabbri","country":"IT"},
  {"company":"Ilaria cozzolino","country":"IT"},
  {"company":"Yasser","country":"LY"},
  {"company":"fabio tappari","country":"IT"},
  {"company":"Rachele Cicero","country":"IT"},
  {"company":"HOPE DI GALLI ALESSIA","country":"IT","sales":"Veronica"},
  {"company":"ANDRULLI DI ANDRILLI VITA MARIA","country":"IT","city":"matera","sales":"Vito"},
  {"company":"Arianna Piras","country":"IT"},
  {"company":"FANCY SIB SRL （散·少一块 安达","country":"RO","sales":"Livio"},
  {"company":"DAREXIM SP. Z O.O. SPOLKA KOMANDYTOWA","country":"PL","city":"Tuszyn","sales":"Veronica"},
  {"company":"Germana","country":"IT"},
  {"company":"PARK PRO S.R.O","country":"CZ","city":"PRAHA","lat":50.0755,"lng":14.4378,"debt":7000.0,"sales":"Livio"},
  {"company":"BLUE ROSE DI GIONNI DUCCIO S.A.S","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Vito"},
  {"company":"alessandrafalchi","country":"IT"},
  {"company":"Vanessa Di Nicola","country":"IT"},
  {"company":"Grace Richards","country":"US"},
  {"company":"Bongiardino","country":"FR"},
  {"company":"Desamparados Hoyos Moreno","country":"ES"},
  {"company":"MD group","country":"PL"},
  {"company":"Charalabos","country":"GR"},
  {"company":"Alin ishak","country":"DZ"},
  {"company":"Boutarbouche","country":"FR"},
  {"company":"Joyce","country":"BE","city":"Beerse"},
  {"company":"Elio BBF FASHION SERV","country":"IT","city":"MELILLI"},
  {"company":"Milan Dulovic","country":"ME"},
  {"company":"FIRMA HANDLOWA “stella”","country":"PL","sales":"Livio"},
  {"company":"SACCO BEATA ANTKOWIAK","country":"PL","city":"Poznań","sales":"Veronica"},
  {"company":"BELLINI HOME 1951 DI EDI BELLINI","country":"IT","sales":"Veronica"},
  {"company":"Zid","country":"RO"},
  {"company":"REIHANRD","country":"DE","city":"Heidenheim an der Brenz","sales":"Livio"},
  {"company":"LOPEZ MAYOS MARIA ISABEL","country":"ES","city":"ESPLUGUES DE LLOBREGAT","sales":"Veronica"},
  {"company":"Debora Marongiu","country":"IT","city":"Santa Margherita Lig"},
  {"company":"TSAKIRIS MALLAS CHAUSSURES","country":"GR","city":"Argyroupoli","sales":"Veronica"},
  {"company":"KONO ALIMAR D.C. SRL 安达","country":"RO","sales":"Livio"},
  {"company":"Angelamaria De Simone","country":"IT"},
  {"company":"UTILE E FUTILE DI METALLI MOMICA","country":"IT","city":"RIMINI","lat":44.0678,"lng":12.5695,"region":"Emilia-Romagna","sales":"Veronica"},
  {"company":"CHESI LAURA","country":"IT","sales":"Veronica"},
  {"company":"MADEME MODE","country":"AT","sales":"Veronica"},
  {"company":"ANA S.R.L.S","country":"IT","city":"CREVALCORE","sales":"Vito"},
  {"company":"SOUFIS GEORGIOS","country":"GR","city":"PARGA","sales":"Vito"},
  {"company":"POKER D‘ASSI DI GASPERONI SARA","country":"SM","city":"Donagnano","sales":"Veronica"},
  {"company":"Alessandro","country":"IT","city":"tortona","lat":44.8943,"lng":8.8643,"region":"Piemonte"},
  {"company":"ALIGATOR BOŻENA GRUCHEL","country":"PL","city":"Jaworze Średnie"},
  {"company":"Lidija Winkelmann","country":"DE"},
  {"company":"BABALOS VASILIS","country":"GR","city":"PALAIO FALIRO ATHENS"},
  {"company":"box color","country":"FR","city":"Juan les pins"},
  {"company":"Gabi Brenner","country":"DE"},
  {"company":"JUST.LUXURY S.C.","country":"PL","sales":"Veronica"},
  {"company":"LOMALEC SARL","country":"FR","sales":"Veronica"},
  {"company":"Bastet K.arnold","country":"PL","sales":"Livio"},
  {"company":"PHU MAD MAX JERZY WITEK","country":"PL","sales":"Veronica"},
  {"company":"阿焌 SH LEDER GMBH","country":"DE","city":"Dreieich","lat":50.0236,"lng":8.7},
  {"company":"Lucia Lazzeretti","country":"IT"},
  {"company":"FARASHA CREATION DI MARIA FALVO","country":"IT","sales":"Veronica"},
  {"company":"AERRE SNC DI CAIO A. E DANTE R.","country":"IT","city":"DESIO"},
  {"company":"Pasquale MANNA","country":"IT"},
  {"company":"BETTY BARCLAY GROUP GMBH CO KG","country":"DE","sales":"Veronica"},
  {"company":"AUTIERO NEW FASHION DI","country":"IT","city":"NAPOLI","lat":40.8518,"lng":14.2681,"region":"Campania"},
  {"company":"MODAEXPRESS 顺","country":"UK","city":"MANCHESTER"},
  {"company":"Eva Karmaniola","country":"GR"},
  {"company":"TABACCHI SASSOLINI RACHELE","country":"IT","sales":"Veronica"},
  {"company":"A.DE MARTINO DESIGN","country":"GR","sales":"Veronica"},
  {"company":"yulanda","country":"DE","sales":"Nico"},
  {"company":"NUNZIA S.A.S","country":"IT","city":"RICCIONE","sales":"Veronica"},
  {"company":"GIULIANO MODE","country":"PL","sales":"Veronica"},
  {"company":"KRISS S.A.S. DI ALBANESE CRISTINA & C.","country":"IT","sales":"Veronica"},
  {"company":"CHIC & CHARME DI CALANCHI ALESSANDRA","country":"IT","sales":"Veronica"},
  {"company":"uğur","country":"TR"},
  {"company":"GIA LA MODA SP.Z.O.O","country":"PL","sales":"Veronica"},
  {"company":"marta coletti","country":"IT","city":"ROMA","lat":41.9028,"lng":12.4964,"region":"Lazio","debt":-223.94},
  {"company":"maria chiara Pandolfo","country":"IT"},
  {"company":"ZWEIRAUM DI SIMONE OLSCHINA","country":"DE","city":"Nurnbery","sales":"Veronica"},
  {"company":"PELLETTERIA TESSA DI TEDESCHI TESSA","country":"IT","sales":"Veronica"},
  {"company":"Hajdana","country":"BA"},
  {"company":"PERAZZO GIOVANNA","country":"IT","sales":"Veronica"},
  {"company":"Imane sellafi","country":"IT"},
  {"company":"Rotondale Shoes Di Maria Antonella Rotondale","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Veronica"},
  {"company":"Claudia Ghimenti","country":"IT"},
  {"company":"Yifat","country":"IL"},
  {"company":"MYOMYA SRL UNIPERSONALE","country":"IT","sales":"Veronica"},
  {"company":"HERZSTUCK MODE","country":"AT","sales":"Veronica"},
  {"company":"MT","country":"IT"},
  {"company":"ZHENG TEXTIL GMBH","country":"DE","city":"ESCHBORN","debt":285.0},
  {"company":"UAB \"Basik\"","country":"LT"},
  {"company":"YVIL MODESCHOENEN EN LEDERWAREN VOF","country":"PL","sales":"Veronica"},
  {"company":"Lucia cameli","country":"IT"},
  {"company":"BAYSAL Esra","country":"FR"},
  {"company":"aldo briciole","country":"IT"},
  {"company":"zhou","country":"IT"},
  {"company":"Cozzo Georgia","country":"IT"},
  {"company":"Rached Mamou","country":"DE"},
  {"company":"Massimiliano croce","country":"IT"},
  {"company":"Santra Sevele","country":"LV"},
  {"company":"BARI STEFANIA","country":"IT"},
  {"company":"Poziomka sklep","country":"PL"},
  {"company":"Fiammetta Dimitri","country":"IT"},
  {"company":"raffaele","country":"IT"},
  {"company":"Arianna biliorsi","country":"IT"},
  {"company":"ATANAS","country":"BG"},
  {"company":"Julian Micallef","country":"MT"},
  {"company":"Agnieszka Makowka","country":"DE"},
  {"company":"Kellner","country":"DE"},
  {"company":"Claudia Bucalo","country":"IT"},
  {"company":"AUGE GÉRALDINE","country":"FR"},
  {"company":"Amit Jain","country":"IE"},
  {"company":"Gissinger","country":"FR"},
  {"company":"Maura Sterlina","country":"IT"},
  {"company":"Eline Corveleyn","country":"BE"},
  {"company":"annaira collection srl","country":"IT"},
  {"company":"Cesare","country":"IT"},
  {"company":"Stella Milici","country":"IT"},
  {"company":"Patrick Chanana","country":"DE"},
  {"company":"sarl fleur de lys","country":"FR"},
  {"company":"Roberta Perrone","country":"IT"},
  {"company":"Cancemi Mariangela","country":"IT"},
  {"company":"simona Laing","country":"IT"},
  {"company":"Deryck sonia","country":"BE"},
  {"company":"Triva Oweid","country":"DE","city":"Marburg"},
  {"company":"MAXIMA SERVICE S.R.O","country":"SK","sales":"Veronica"},
  {"company":"MAROLYS BAT242","country":"FR","sales":"Vito"},
  {"company":"GLT PARIS LOGISTICS COMPRAS ITALIA","country":"FR","city":"AUBERVILLIERS","lat":48.9131,"lng":2.3835,"sales":"Veronica"},
  {"company":"ELEVEN","country":"GR","city":"THESSALONNIKH-GREECE"},
  {"company":"MATTIOLI NICOSIA LUISA LOLANDA","country":"IT","sales":"Veronica"},
  {"company":"ZORMAX","country":"PL"},
  {"company":"SAC D'ENFER SARL ANDREE","country":"FR","sales":"Veronica"},
  {"company":"SARL FLEUR DE LYS","country":"FR","sales":"Veronica"},
  {"company":"Michele Ceccolini","country":"IT"},
  {"company":"GIVAL OOD","country":"BG","sales":"Veronica"},
  {"company":"Bellosta Morlans","country":"ES"},
  {"company":"SUNNY MODE GMBH","country":"DE","sales":"Veronica"},
  {"company":"BVBA MAXIMS FASHION","country":"BE","city":"ROESELARE","sales":"Veronica"},
  {"company":"VALENTI FESHION LTD","country":"BG","sales":"Veronica"},
  {"company":"KLUB USLUGE D.O.O","country":"HR","sales":"Veronica"},
  {"company":"scher","country":"DE"},
  {"company":"MACAMA DI VIRGALLITO CARMELA","country":"IT","sales":"Veronica"},
  {"company":"LI LEDERWAREN GMBH","country":"DE","city":"HAMBURG GERMANY"},
  {"company":"RAVELLA 1898 S.N.C","country":"IT","sales":"Veronica"},
  {"company":"CARENO FASHION","country":"IL","sales":"Veronica"},
  {"company":"BUTIK IZKUSHENIE EOOD","country":"BG","sales":"Veronica"},
  {"company":"FENAROLI VITTORIA","country":"IT","sales":"Veronica"},
  {"company":"VITTORIA EXCELLENCE OF TUSCANY S.R.L","country":"IT","city":"CASCIANA TERME LARI","sales":"Veronica"},
  {"company":"PROFUMERIA FEDERICA","country":"IT","city":"SERRAVALLE PISTOIESE","sales":"Vito"},
  {"company":"Tiziana Genovese","country":"IT"},
  {"company":"ROADIS SAS RAYON TEXTILE","country":"FR","sales":"Veronica"},
  {"company":"Daniela d’arco","country":"IT"},
  {"company":"matteo","country":"IT","city":"genova","lat":44.4056,"lng":8.9463,"region":"Liguria"},
  {"company":"HENRY & JAMES FASHION TRADING","country":"DE","sales":"Veronica"},
  {"company":"SARL MAZZ","country":"FR","sales":"Veronica"},
  {"company":"GIO‘FASHION DI PICAZIO GIOVANNA","country":"IT","sales":"Veronica"},
  {"company":"EMME LAB STERLINA MAURA","country":"IT","sales":"Veronica"},
  {"company":"HONEST S.R.L","country":"IT","sales":"Veronica"},
  {"company":"MASS d.o.o.","country":"SI","city":"Domzale","sales":"Nico"},
  {"company":"LA BUSSOLA VENTAG","country":"IT","city":"RIMINI","lat":44.0678,"lng":12.5695,"region":"Emilia-Romagna","sales":"Veronica"},
  {"company":"ANSWEAR.COM S.A.","country":"PL","sales":"Livio"},
  {"company":"FARMACIA COMUNALI RIUNITE S.P.A","country":"IT","sales":"Veronica"},
  {"company":"RISTORI EZIO","country":"IT","sales":"Veronica"},
  {"company":"Ευαγγελία Γιαμούκογλου","country":"GR"},
  {"company":"Mai-Britt","country":"DK"},
  {"company":"NART SRL ANTONIO","country":"IT","sales":"Livio"},
  {"company":"KRISTY ABBIGLIAMENTO DI NIZZOLI MARIA CRISTINA","country":"IT","city":"Fiorano Modenese","sales":"Veronica"},
  {"company":"Monika Karpiuk","country":"PL"},
  {"company":"Татьяна Валентиновна Долотон","country":"RU"},
  {"company":"tag1979@libero.it","country":"IT"},
  {"company":"VANITIES SRL","country":"SM","sales":"Veronica"},
  {"company":"Souib yamna","country":"IT"},
  {"company":"LILA MODA","country":"BE","sales":"Livio"},
  {"company":"SARL EST OUEST","country":"FR","sales":"Veronica"},
  {"company":"MANIFATTURE TOSCANE*TA-BRU S.P.A.","country":"IT","sales":"Veronica"},
  {"company":"ANHKO ADAM KOLODZIEJSKI","country":"PL","sales":"Veronica"},
  {"company":"MUFFIN DI STEFAN LA","country":"IT","city":"SCANDIANO","sales":"Veronica"},
  {"company":"ANASTASIA","country":"GR"},
  {"company":"Natalia Żuchowska GlossyDot","country":"PL"},
  {"company":"Maria Lasala","country":"IT"},
  {"company":"Mari Fuente","country":"PT"},
  {"company":"Luana Cristo","country":"IT"},
  {"company":"THRRE DIAMONDS DOO","country":"BG","sales":"Livio"},
  {"company":"J.ELLE DI FABOZZI LUIGI JUNIOR","country":"IT","sales":"Veronica"},
  {"company":"SC VALMAT","country":"RO","city":"SAT BRANCENI COM. BRANCENI","sales":"Livio"},
  {"company":"Mariella Morelli","country":"IT","city":"MONTEPRANDONE (AP)"},
  {"company":"Linda Fumagalli","country":"IT"},
  {"company":"Ghersin Tatjana","country":"BE"},
  {"company":"Patti","country":"BE"},
  {"company":"Petra maas","country":"NL"},
  {"company":"留树彬老婆","country":"SK"},
  {"company":"OLYGEMS OLIWIA MAZUR","country":"PL","sales":"Veronica"},
  {"company":"SABBIAROSA DI COPPOLA ROBERTO PIRTRO","country":"IT","sales":"Veronica"},
  {"company":"LULLI DAURA","country":"IT","sales":"Veronica"},
  {"company":"ANCHACA DI ANNE CHARLOTTE CASCELLA","country":"IT","debt":-85.0,"sales":"Veronica"},
  {"company":"Micaela Fullone","country":"IT"},
  {"company":"wiegandt","country":"CH"},
  {"company":"SARA IANNETTI S.R.L","country":"IT","city":"ROMA","lat":41.9028,"lng":12.4964,"region":"Lazio","sales":"Veronica"},
  {"company":"PAULINA KOPIEC","country":"PL","city":"Tarnów","sales":"Veronica"},
  {"company":"SEQULIN","country":"PL","sales":"Livio"},
  {"company":"Marie Cannella","country":"BE"},
  {"company":"Giannis","country":"GR"},
  {"company":"BDIFFERENT","country":"NL","city":"NC KERKRADE"},
  {"company":"Blanche Kannekens","country":"NL"},
  {"company":"PRETTY MODE","country":"FR","city":"MARSEILLE","lat":43.2965,"lng":5.3698},
  {"company":"cihan","country":"TR"},
  {"company":"Dalit Peer","country":"IL"},
  {"company":"Mihail","country":"RO"},
  {"company":"Carpe Diem","country":"SK"},
  {"company":"Pikiner Liudmyla","country":"PL"},
  {"company":"FONTANA STEFANO","country":"IT","sales":"Veronica"},
  {"company":"CASSI AGNIESZKA NADOLDA","country":"PL","sales":"Veronica"},
  {"company":"CR S.R.L","country":"IT","sales":"Veronica"},
  {"company":"hoskens lieve","country":"BE","city":"vrasene"},
  {"company":"bart vauterin","country":"BE","city":"Kortrijk"},
  {"company":"MODA BORSE","country":"CS","sales":"Veronica"},
  {"company":"E-LONG HANDELS MODE TASCHEN LUI YAN KEG","country":"AT","city":"WIEN-AUSTRIA"},
  {"company":"NEO CHIC DI LAPI SILVIA","country":"IT"},
  {"company":"Junio Giuseppe Falcone","country":"IT","city":"Reggio Calabria"},
  {"company":"manigand","country":"FR"},
  {"company":"heidy tobar","country":"US"},
  {"company":"Bizermiania Constantina","country":"GR","city":"Athens","lat":37.9838,"lng":23.7275},
  {"company":"MAKRA SRLS","country":"IT","city":"ROCCABASCERANA","sales":"Veronica"},
  {"company":"Sermo Felino","country":"FR"},
  {"company":"MOSCARDI SANDRA","country":"IT","city":"CALENZANO","sales":"Veronica"},
  {"company":"MC 导师 Jenny","country":"IT"},
  {"company":"Lucia","country":"IT","city":"NOLA","sales":"Veronica"},
  {"company":"STRIANO BIANCHERIA DI CIMMINO CELESTINA","country":"IT","city":"PAGANI","sales":"Veronica"},
  {"company":"andrea pepi","country":"IT"},
  {"company":"fen","country":"IT"},
  {"company":"OSNAT BEN AMI","country":"IS","sales":"Veronica"},
  {"company":"FIRMA HANDLOW USLUGOWA KOS STEFAN","country":"PL","sales":"Veronica"},
  {"company":"Szável Brigitta","country":"HU"},
  {"company":"Alix melissa","country":"FR"},
  {"company":"G.GLAMOUR DI RICCIO ANTONIETTA","country":"IT","sales":"Veronica"},
  {"company":"BAGSO INTERNATIONAL LTD","country":"BG","city":"гр.ГАБРОВО","sales":"Veronica"},
  {"company":"Maria Isabel Lopez Mayos","country":"ES"},
  {"company":"Marika Arrotini","country":"IT"},
  {"company":"ana moreira","country":"PT"},
  {"company":"Dan Ticea","country":"RO"},
  {"company":"BL SILVER&BIJOUX DI LUCIA MERELLI","country":"IT","city":"MONTE SAN SAVINO","sales":"Vito"},
  {"company":"Roberta Barrasso","country":"IT"},
  {"company":"ANNA S.R.L","country":"IT","city":"SALERNO","sales":"Veronica"},
  {"company":"AMARA S.R.L.S","country":"IT","city":"TEATINO","sales":"Veronica"},
  {"company":"cynthia","country":"LB"},
  {"company":"nursah","country":"TR"},
  {"company":"alexia markou","country":"GR"},
  {"company":"matteo cervi","country":"IT"},
  {"company":"Tomasevic","country":"LT"},
  {"company":"fatima zahra","country":"MA"},
  {"company":"Anja Jovicevic","country":"ME"},
  {"company":"Kahyaoglu","country":"TR"},
  {"company":"mercatelli stefania","country":"IT"},
  {"company":"Tanja Jandrić","country":"HR","city":"Mali Lošinj","debt":-275.4},
  {"company":"TARALÌ","country":"IT"},
  {"company":"CONCPT RAGHBIR SINGH","country":"DE","sales":"Veronica"},
  {"company":"SARL LE CAVALIER EUROPE","country":"FR","city":"BOURGOIN-JALLIEU","sales":"Veronica"},
  {"company":"top moda","country":"PL"},
  {"company":"Chiara Vinciguerra","country":"IT"},
  {"company":"INTERIORHUSET AB","country":"SE","city":"hallingsjo"},
  {"company":"TORFS L. NV","country":"BE","city":"SINT-NIKLAAS","sales":"Veronica"},
  {"company":"Eleonora fabbo","country":"IT"},
  {"company":"Valentina Russo","country":"IT"},
  {"company":"THEODOULIDOU K.ARGYRO","country":"GR","city":"ΘΕΣΣΑΛΟΝΙΚΗ","sales":"Veronica"},
  {"company":"ENA GROUP C/O EAG INVEST 443","country":"LB","sales":"Veronica"},
  {"company":"PELLETERIE ZANETTA S.R.L","country":"IT","city":"AOSTA","sales":"Veronica"},
  {"company":"APK FASTIGHETER AB","country":"SE","city":"HÄLLINGSJÖ","sales":"Veronica"},
  {"company":"vlbg","country":"RS"},
  {"company":"FRIDA DI MARCONI SILVIA","country":"IT","city":"CATTOLICA","sales":"Vito"},
  {"company":"ESTER SRL PRATO","country":"IT","sales":"Livio"},
  {"company":"ANTON DORFLER","country":"DE","city":"Landshut","sales":"Veronica"},
  {"company":"LA SUPER EDICOLA DI IRENE BARSANTI","country":"IT","city":"SAN MARCELLO PITEGLIO","sales":"Veronica"},
  {"company":"ANIMA DI BALDINI ANNA","country":"IT","city":"CREVALCORE","sales":"Veronica"},
  {"company":"MODE OUTLET WECKERLE","country":"DE","sales":"Veronica"},
  {"company":"fiere di moda","country":"PL","city":"Bądzyń","sales":"Nico"},
  {"company":"Gioia Xu","country":"IT"},
  {"company":"JOANNA BURCHARDT","country":"PL","city":"GDAŃSK","sales":"Veronica"},
  {"company":"myla","country":"IT"},
  {"company":"LA MANNA DI PANCALDI ANTONELLA","country":"IT","city":"BUDRIO","sales":"Veronica"},
  {"company":"POKER D ASSI","country":"SM","sales":"Veronica"},
  {"company":"FIRST SNC DI ZANICHELLI ILENIA","country":"IT","city":"ZOLA PREDOSA","sales":"Veronica"},
  {"company":"sara gasperoni","country":"SM"},
  {"company":"ARTE E FANTASIA FIRENZE DI CORONA STEFANIA","country":"IT","city":"CARMIGNANO","sales":"Vito"},
  {"company":"Hosenshop Gmbh","country":"DE","sales":"Veronica"},
  {"company":"ZG老账","country":"IT","city":"Padova","lat":45.4064,"lng":11.8768,"region":"Veneto"},
  {"company":"Miss May Xiner","country":"AT","sales":"Livio"},
  {"company":"FASHION STAR DI PARRONI SONIA","country":"IT","city":"RAVENNA","sales":"Veronica"},
  {"company":"Mari S.R.L","country":"IT","city":"GENOVA","lat":44.4056,"lng":8.9463,"region":"Liguria","sales":"Veronica"},
  {"company":"AGATA RUDZINSKA","country":"PL","city":"WIELKOPOLSKI","sales":"Vito"},
  {"company":"DESPY KBOUTIQUE MONOPROSOPI IKE","country":"GR","city":"Peristeri","sales":"Vito"},
  {"company":"GAZZE LADRE S.A.S DI MILLOZZI MAURA E C.","country":"IT","city":"CASTELLANA","sales":"Vito"},
  {"company":"MIKAL DIbBANDIRINI MICHEL","country":"IT","city":"SUZZARA","sales":"Veronica"},
  {"company":"DARIUSZ FIJAK","country":"PL","city":"KOŚCIELNY","sales":"Veronica"},
  {"company":"A MANO A MANO DI CAPIGIRI ANTONELLA","country":"IT","city":"CASTEL FOCOGNANO","sales":"Vito"},
  {"company":"Primatex - 2 ooD","country":"BG","city":"Varna","sales":"Vito"},
  {"company":"Patric arkadius","country":"PL","city":"SANTOCKA","sales":"Veronica"},
  {"company":"Fischer & Fröhlich","country":"DE"},
  {"company":"olivi","country":"IT"},
  {"company":"Gessica Buonomo","country":"IT"},
  {"company":"stefania picconino","country":"IT"},
  {"company":"Stefania Piccinini","country":"IT"},
  {"company":"ESTETICA SERENA","country":"IT","city":"CENTRO VALLE INTELVI"},
  {"company":"Cristina Migone","country":"IT","city":"GENOVA","lat":44.4056,"lng":8.9463,"region":"Liguria"},
  {"company":"XANTROCOSMOS LIMITED","country":"GR","city":"Korydallos"},
  {"company":"Manon Buzzano","country":"CH"},
  {"company":"UMERIA L ETOILE DI CORUZZI ANNA","country":"IT","city":"FONTEVIVO"},
  {"company":"sas les agapes","country":"FR","sales":"Vito"},
  {"company":"Maria Bartolo","country":"IT","city":"CASTELLAMMARE DEL GOLFO"},
  {"company":"fortino Nicola","country":"IT","city":"COSENZA"},
  {"company":"Marta","country":"IT","city":"ROMA","lat":41.9028,"lng":12.4964,"region":"Lazio"},
  {"company":"Daniela Maligheti","country":"IT","city":"BRIVIO"},
  {"company":"Susana Ribeiro Calva","country":"CH"},
  {"company":"Francesca","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia"},
  {"company":"Paolo Genova","country":"IT","city":"GENOVA","lat":44.4056,"lng":8.9463,"region":"Liguria"},
  {"company":"francesco roccella","country":"IT"},
  {"company":"DeGanis","country":"IT","city":"ARCORE"},
  {"company":"sandra","country":"IT","city":"PORTOGRUARO"},
  {"company":"Sandra Battel","country":"IT"},
  {"company":"Vivere","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia"},
  {"company":"Marcella Parravicini","country":"IT"},
  {"company":"Gabriele","country":"IT","city":"PALERMO","lat":38.1157,"lng":13.3613,"region":"Sicilia"},
  {"company":"mari srl","country":"IT"},
  {"company":"MariaRosa","country":"IT","city":"SONDRIO"},
  {"company":"TACUMABEN DI MASSETTI MANIELA","country":"IT","city":"ACQUI TERME","sales":"Veronica"},
  {"company":"MAD S.R.L.S","country":"IT","city":"Roma","lat":41.9028,"lng":12.4964,"region":"Lazio","sales":"Veronica"},
  {"company":"Jade Fernando","country":"US"},
  {"company":"Alessandro bianco","country":"IT"},
  {"company":"Yenifer Lara","country":"DO"},
  {"company":"ANNE CHARLOTTE CASCELLA","country":"IT","city":"Lecce","sales":"Veronica"},
  {"company":"eveline Deboutte","country":"BE"},
  {"company":"Vincenzo Luciani","country":"IT"},
  {"company":"OAZIS MZ LTD","country":"BG","city":"DIMITROVGRAD"},
  {"company":"Florea Andrei","country":"RO"},
  {"company":"marco Polonia","country":"PL"},
  {"company":"ARTICLES DE PARIS","country":"FR","city":"BORDEAUX","sales":"Veronica"},
  {"company":"jeremie","country":"FR"},
  {"company":"Filippo Bartolini","country":"IT"},
  {"company":"gkekas","country":"IT"},
  {"company":"MONTICELLI VALERIO","country":"IT","city":"ABETONE CUTIGLIANO","sales":"Veronica"},
  {"company":"BAMBI PATRIZIA","country":"IT","city":"VIAREGGIO","lat":43.8664,"lng":10.2503,"region":"Toscana","sales":"Veronica"},
  {"company":"MB..MANO FORMA","country":"LT","city":"Palangos m. sav.","sales":"Veronica"},
  {"company":"ZIMMERMANN HANDELS GMBH","country":"AT","city":"KLAGENFURT","sales":"Veronica"},
  {"company":"Alba Garcia","country":"ES"},
  {"company":"Ramon Riera","country":"ES"},
  {"company":"silvush85@gmail.com","country":"IT","city":"Rapallo"},
  {"company":"Elena Cappelli","country":"IT"},
  {"company":"GGM GROUP S.R.L","country":"IT","city":"NAPOLI","lat":40.8518,"lng":14.2681,"region":"Campania","sales":"Veronica"},
  {"company":"AL.COVA S.A.S. DI VALENTINA CONVERSO","country":"IT","city":"VALLECROSIA","sales":"Veronica"},
  {"company":"GIOIELLERIA POLLONI DI ALESSANDRA","country":"IT","city":"SARTEANO","sales":"Veronica"},
  {"company":"yang","country":"IT"},
  {"company":"Francesca Migni","country":"IT"},
  {"company":"Manuela de Virgilio","country":"IT"},
  {"company":"Gely Emmanouilidou","country":"GR"},
  {"company":"LA SAPIENZA GALLERIA DI CARLI LETIZIA","country":"IT","city":"SIENA","sales":"Veronica"},
  {"company":"Alessandra Polloni","country":"IT"},
  {"company":"MON AMOUR BOUTIQUE DI ELISA MONTEPARANI","country":"IT","city":"CARMIGNANO","sales":"Veronica"},
  {"company":"ENGKVIST，CAMILLA","country":"SE","city":"STENHAMRA","sales":"Veronica"},
  {"company":"Camilla","country":"SE"},
  {"company":"GRUPPO STILE DE VIRGILIO","country":"IT","city":"MOLFETTA","sales":"Veronica"},
  {"company":"SANDROS CRUZ ACCESSORIES S.L","country":"ES","city":"MADRID ESPANA"},
  {"company":"GAZZE LADTE SAS","country":"IT","city":"CIVITA CASTELLANA","sales":"Vito"},
  {"company":"GLAMOUR DI SIMONTI FRANCESCA","country":"IT","city":"LIVORNO","sales":"Vito"},
  {"company":"FAIS JEANS S.R.L","country":"IT","city":"GROSSETO","sales":"Veronica"},
  {"company":"mina2","country":"IT"},
  {"company":"Virginia Grassi","country":"IT"},
  {"company":"KAN KOMERS 2014 EOOD","country":"BG","city":"DIMITROVGAD"},
  {"company":"ELIDEMA S.R.L.","country":"IT","city":"AREZZO","sales":"Vito"},
  {"company":"amal","country":"LB"},
  {"company":"JMaria","country":"SK","city":"Zubrohlava"},
  {"company":"Hurtownia TOREBEK sevills","country":"PL","sales":"Livio"},
  {"company":"TRADE UP MILNAD SAS","country":"IT","city":"CARPI","sales":"Livio"},
  {"company":"Agnieszka Zygnerska","country":"PL"},
  {"company":"Ouyue luggage 欧跃箱包","country":"ES","city":"Palma mallorca"},
  {"company":"kdadry","country":"IT"},
  {"company":"sxxb","country":"IT"},
  {"company":"NATKA SPOL. S.R.O.","country":"CZ","city":"PRAHA","lat":50.0755,"lng":14.4378,"sales":"Veronica"},
  {"company":"MIKELINA FASHION","country":"GR","city":"ΣΠΑΤΑ","sales":"Vito"},
  {"company":"JLB GILARI","country":"FR","city":"LYON","lat":45.764,"lng":4.8357,"sales":"Vito"},
  {"company":"ROSA SRL","country":"IT","city":"MAGLIE","sales":"Vito"},
  {"company":"DOMINO MATGORZATA NESTMANN","country":"PL","city":"DWORCOWA","sales":"Vito"},
  {"company":"WHY NOT? DI ARDITO EDOARDO","country":"IT","city":"CARRARA","sales":"Vito"},
  {"company":"INTERNO TREDICI DI BENIGNI EMANUELE","country":"IT","city":"AREZZO","sales":"Vito"},
  {"company":"natasha montenegro","country":"ME"},
  {"company":"SONNINI","country":"CZ","city":"CESKY BROD"},
  {"company":"Anne Sauro","country":"NO"},
  {"company":"ANTICA TABACCHERIA DI CHIARA CLAUDIO","country":"IT","city":"CHIANA","sales":"Vito"},
  {"company":"Flavio Busoni","country":"IT"},
  {"company":"MIGUEL ANGEL ARAMENDIA SIZE ONE SL","country":"ES","sales":"Vito"},
  {"company":"dyfashion","country":"RO"},
  {"company":"TRUPIA GIANFRANCO","country":"IT","city":"PRATO","lat":43.8777,"lng":11.0955,"region":"Toscana","sales":"Veronica"},
  {"company":"Sara Romboni","country":"IT"},
  {"company":"NINA.S DI SBARDOLINI ALICE","country":"IT","city":"LISSONE","sales":"Veronica"},
  {"company":"CREATIVA S.N.C DI SCANU ROSETTA & C","country":"IT","city":"RICCIONE","sales":"Vito"},
  {"company":"Stanislav Todev","country":"BG"},
  {"company":"CONTRAST AS L.Z.D","country":"BG","city":"Haskovo","sales":"Vito"},
  {"company":"maxmorelli73@gmail.com","country":"IT"},
  {"company":"CALIENTE TEX LTD","country":"BG","city":"Burgas","sales":"Vito"},
  {"company":"CALZATURA FERECCIO DI ELISA FERECCIO","country":"IT","city":"BOGLIASCO","sales":"Vito"},
  {"company":"GRAZYNA PASZKO","country":"PL","city":"Kostrzyn Nad Odrą","sales":"Vito"},
  {"company":"arena rosalia","country":"IT"},
  {"company":"TRENDY BAGS HEIDELBERG","country":"DE","sales":"Vito"},
  {"company":"ADRIACART","country":"IT","city":"PORTO SANT'ELPIDIO","sales":"Livio"},
  {"company":"Bartolini","country":"IT"},
  {"company":"DITTA TUGNOLI DI TUGNOLI ANGELO","country":"IT","city":"MOLINELLA","sales":"Vito"},
  {"company":"BARTOLINI RAMONA","country":"IT","city":"SAN GIOVANNI IN MARIGNANO","sales":"Veronica"},
  {"company":"GENOVIA","country":"IT","city":"BARI","lat":41.1171,"lng":16.8719,"region":"Puglia","sales":"Veronica"},
  {"company":"Sofia Di Gennaro","country":"IT"},
  {"company":"KYRIAKI TOYLIDOU","country":"GR","city":"ΚΑΣΣΑΝΔΡΕΙΑ","sales":"Vito"},
  {"company":"Buzila Florentina","country":"RO"},
  {"company":"татяна иванчева","country":"BG"},
  {"company":"ignacio","country":"IT"},
  {"company":"AEMME SRL","country":"IT","city":"MONZA","sales":"Vito"},
  {"company":"Mattia bertano","country":"IT"},
  {"company":"TAM FASHIO GMBH","country":"DE","city":"Michelfeld","sales":"Veronica"},
  {"company":"PRIMITIVE SRL","country":"IT","city":"ROMA","lat":41.9028,"lng":12.4964,"region":"Lazio","sales":"Vito"},
  {"company":"MODA POLSKA","country":"PL","city":"KROSNO","sales":"Vito"},
  {"company":"michaela fridlova","country":"CZ"},
  {"company":"Michaela","country":"CZ"},
  {"company":"LEMONGRASS DI CLAUDIO URCIUOLO","country":"IT","city":"SAN MINIATO","sales":"Vito"},
  {"company":"Ksenia Vorontsova","country":"GB"},
  {"company":"adnan","country":"BE"},
  {"company":"MARLIN DI SCORCELLETTI CINZA","country":"IT","city":"MATELICA","sales":"Veronica"},
  {"company":"PRIMADONA","country":"PT","city":"VALONGO","sales":"Livio"},
  {"company":"Johnny","country":"IT"},
  {"company":"SKY STELLA SRL","country":"IT","city":"CAGLIARI","lat":39.2238,"lng":9.1217,"region":"Sardegna","sales":"Veronica"},
  {"company":"BRICIOLE S.R.L","country":"IT","city":"FIORENTINO","sales":"Veronica"},
  {"company":"SHACKSON LTD","country":"BG","sales":"Livio"},
  {"company":"Eleonora Gaspodini","country":"IT"},
  {"company":"PINKDOOR DI MANUELA GOKINAJEW","country":"IT","city":"MELZO","sales":"Veronica"},
  {"company":"denis","country":"FR"},
  {"company":"eva","country":"FR"},
  {"company":"Christina Sommerstedt","country":"DK"},
  {"company":"老娘芬CARLA INGROSSO di Lin wang mei","country":"IT","city":"Palermo","lat":38.1157,"lng":13.3613,"region":"Sicilia"},
  {"company":"阿青 Good Hope Bags gmbh","country":"DE","city":"Dreieich","lat":50.0236,"lng":8.7},
  {"company":"CHRISTINA","country":"GR"},
  {"company":"Felicia","country":"RO"},
  {"company":"Marian Natu","country":"RO"},
  {"company":"MADAME SHOES BAGS","country":"GR","city":"Kato Achaia","sales":"Veronica"},
  {"company":"OUTFIT DESIGN BY MADELIA S.R.L","country":"RO","sales":"Veronica"},
  {"company":"FARMACIA BOSCARINO S.R.","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Veronica"},
  {"company":"eleuteri","country":"IT"},
  {"company":"Jula Adina","country":"RO"},
  {"company":"孙凯希","country":"AT"},
  {"company":"barbara ciciotti","country":"IT"},
  {"company":"IDETOS S.R.L","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Veronica"},
  {"company":"SEYLI KFT.","country":"HU","city":"BUDAPEST","lat":47.4979,"lng":19.0402,"sales":"Veronica"},
  {"company":"BELLA STORE","country":"CZ","city":"Praha - Nové Město","sales":"Veronica"},
  {"company":"kioulpekian kleopatra","country":"GR"},
  {"company":"Davide Vitale","country":"DE"},
  {"company":"VASTO STYLE BARBARA BRZOZ","country":"PL","city":"Sosnowiec","sales":"Veronica"},
  {"company":"angela carafa","country":"IT"},
  {"company":"ramona pardini","country":"IT"},
  {"company":"Edoardo Ardito","country":"IT"},
  {"company":"Barbieri Elisa","country":"IT"},
  {"company":"Ellen Vander Putten","country":"BE"},
  {"company":"Isaac Brigitte","country":"FR"},
  {"company":"Antonio Maggiore","country":"IT"},
  {"company":"Amer Murad","country":"NL"},
  {"company":"paulina aleksanderek-czykieta","country":"PL"},
  {"company":"Guangdong","country":"IT"},
  {"company":"NO TABU GMBH","country":"DE","city":"LUDWIGSBURG","sales":"Veronica"},
  {"company":"J&W BA","country":"BE","sales":"Veronica"},
  {"company":"AIVY GMB","country":"DE","city":"SAARBRUCKEN","sales":"Veronica"},
  {"company":"WE 4","country":"DE","sales":"Vito"},
  {"company":"OLIPIA 2001 S.R.L","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia","sales":"Vito"},
  {"company":"Mehmet Ali","country":"DE"},
  {"company":"ARTECAPELLI DI DEL FABBRO SABRI","country":"IT","city":"PASIANO DI PORDENONE","sales":"Veronica"},
  {"company":"S.C. ECO BAG S.R.L","country":"RO","city":"COMUNA ARONEANU, SAT ARONEANU","sales":"Veronica"},
  {"company":"CALIMALA 31Srl","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Livio"},
  {"company":"LOGO HOLDING INTERMED","country":"RO","city":"PITESTI","sales":"Veronica"},
  {"company":"Rocio Rodriguez Vega","country":"ES"},
  {"company":"Muriel CHAIZE ARGAUD","country":"FR"},
  {"company":"SOLINAS ISIDE","country":"IT","city":"ALGHERO","sales":"Vito"},
  {"company":"Jean-Charles Gimbrere","country":"BE"},
  {"company":"koke boutique","country":"GR"},
  {"company":"Cristina Rodríguez Pérez","country":"ES"},
  {"company":"Massimo","country":"IT"},
  {"company":"VIAVENTI DI BELVISI FEDERI","country":"IT","city":"SINALUNGA","sales":"Veronica"},
  {"company":"MME MONCHERA MARIE LUCIE","country":"FR","city":"BASTIA","sales":"Veronica"},
  {"company":"FREIRAUM","country":"DE","sales":"Veronica"},
  {"company":"petarhir","country":"RS"},
  {"company":"BLUE SHOP GMBH & CO.KG","country":"DE","sales":"Veronica"},
  {"company":"COTES ET LIN NICE","country":"FR","city":"NICE","lat":43.7102,"lng":7.262,"sales":"Veronica"},
  {"company":"IL ROSETO LUXURY STORE DI MIGLIOSI ROSI","country":"IT","city":"ASSISI","sales":"Veronica"},
  {"company":"MORADEI ALESS","country":"IT","city":"CAMPI BISENZIO","sales":"Vito"},
  {"company":"DAPHNE S.R.L","country":"IT","city":"SANREMO","sales":"Veronica"},
  {"company":"NEW TRADE GM","country":"AT","city":"Hohenems","sales":"Veronica"},
  {"company":"KONSTANTINOS A.SPYROPOULOS AND CO EE","country":"GR","city":"Thessaloniki","lat":40.6401,"lng":22.9444,"sales":"Veronica"},
  {"company":"TIRIAKIDIS P.8 SONS","country":"GR","city":"Maroussi","sales":"Veronica"},
  {"company":"FERRARI MARCO","country":"IT","city":"CASINA","sales":"Veronica"},
  {"company":"elisa berti","country":"IT"},
  {"company":"MARKOS SAMARAS","country":"GR","city":"ΣΙΑΤΙΣΤΑ","sales":"Veronica"},
  {"company":"CHRIATOS GITERSO","country":"GR","city":"ΚΑΛΛΙΘΕΑ","sales":"Veronica"},
  {"company":"FRATELLI PETRIDI I.KE","country":"GR","city":"ΘΕΣΣΑΛΟΝΙΚΗ","sales":"Veronica"},
  {"company":"FOLLEY S.R.L","country":"IT","city":"ROMA","lat":41.9028,"lng":12.4964,"region":"Lazio","sales":"Veronica"},
  {"company":"fanatikerie","country":"IT"},
  {"company":"Therese","country":"SE"},
  {"company":"Monia Tafuro","country":"IT"},
  {"company":"BETTY FLOFRENCE S.N.C","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Veronica"},
  {"company":"Mohammed","country":"DE"},
  {"company":"BARUCCI ANTONELLa","country":"IT","city":"TERRANUOVA BRACCIOLINI","sales":"Veronica"},
  {"company":"Laura","country":"LT"},
  {"company":"maryna bukhmet","country":"IT"},
  {"company":"ROGA S.R.L.S","country":"IT","city":"POTENZA","sales":"Veronica"},
  {"company":"MA GIA DI MATERAZZI S.&GIALLI L.S.N.","country":"IT","city":"MONTE SAN SAVINO","sales":"Veronica"},
  {"company":"GARMENT STORE","country":"BG","city":"Karlovo","sales":"Veronica"},
  {"company":"Nikki Eeckelaers","country":"BE"},
  {"company":"ANTONIA GODOY MARTOS","country":"ES","city":"OLOT","sales":"Veronica"},
  {"company":"D‘SOCKA SOCIETA COOPERATIVA","country":"IT","city":"GRESSONEY SAINT JEAN","sales":"Veronica"},
  {"company":"Ricardo Santos","country":"PT"},
  {"company":"Natalja Zincenko","country":"LV"},
  {"company":"Dauchy","country":"FR"},
  {"company":"Melanie","country":"BE"},
  {"company":"Andrea costanzo iorio","country":"IT"},
  {"company":"elena pluchinotta","country":"IT"},
  {"company":"Maria luisa Goicoechea","country":"ES"},
  {"company":"DONNASIMO DI FEDERICO SIMONA","country":"IT","city":"SERAVEZZA","sales":"Veronica"},
  {"company":"Anders","country":"DE"},
  {"company":"MASSY SRL","country":"IT","city":"Prato","lat":43.8777,"lng":11.0955,"region":"Toscana"},
  {"company":"PRISMA S.A.S di lippi paolo","country":"IT","city":"ROMA","lat":41.9028,"lng":12.4964,"region":"Lazio","sales":"Veronica"},
  {"company":"MILNAD SAS","country":"FR","city":"BOULOGNE-BILLANCOURT","sales":"Veronica"},
  {"company":"UN‘IDEA IN PIU DI TERESA BRUNETTI","country":"IT","city":"AGLIANA","sales":"Veronica"},
  {"company":"ANDERS DIE MO","country":"DE","sales":"Veronica"},
  {"company":"EPONESHOP S.R.O.","country":"SK","city":"Košice - mestská časť Západ","sales":"Veronica"},
  {"company":"法国阿建 I-BAG","country":"FR"},
  {"company":"violeta","country":"LT"},
  {"company":"Usman","country":"IE"},
  {"company":"Lili Maistruc","country":"RO"},
  {"company":"MODA CLUB PL sp.z.o.o sp.kom","country":"PL","city":"RZGOW.ul"},
  {"company":"Grace","country":"US"},
  {"company":"susan harrid","country":"UM"},
  {"company":"Scott Chatdens","country":"US"},
  {"company":"Chris","country":"US"},
  {"company":"Papp Barbara","country":"HU"},
  {"company":"Van Deuren Wendy","country":"BE"},
  {"company":"Cristian","country":"RO"},
  {"company":"chen","country":"IT"},
  {"company":"Jamie Dela Cruz","country":"AU"},
  {"company":"tomei","country":"IT"},
  {"company":"fillipi","country":"IT"},
  {"company":"Peter","country":"NL"},
  {"company":"Charis Iakovidis Ltd","country":"CY"},
  {"company":"zhanina asenova angelova","country":"NL"},
  {"company":"yazid","country":"GB"},
  {"company":"kikrea di Giometti J e Vanzetti S","country":"IT"},
  {"company":"marco santoianni","country":"IT"},
  {"company":"salvatore rossi","country":"IT"},
  {"company":"tudor","country":"RO"},
  {"company":"cristina mirmi barranca","country":"ES"},
  {"company":"NATALYA MKTCHYAN","country":"AT","sales":"Veronica"},
  {"company":"Aurora Messineo","country":"IT"},
  {"company":"AAlessandro","country":"IT"},
  {"company":"va","country":"IT"},
  {"company":"Birgit Fechner","country":"DE"},
  {"company":"institut de mode","country":"FR"},
  {"company":"Saskia Devriere","country":"BE"},
  {"company":"tomasz","country":"PL"},
  {"company":"joyce mstach","country":"BE"},
  {"company":"Nikol","country":"SK"},
  {"company":"nasro","country":"DZ"},
  {"company":"MINOU CALZATURE","country":"IT","city":"PIAZZA AL SERCHIO","sales":"Veronica"},
  {"company":"光斌","country":"IT","city":"VERONA","lat":45.4384,"lng":10.9916,"region":"Veneto"},
  {"company":"Sara Francioli","country":"IT"},
  {"company":"Anna Faivre","country":"FR"},
  {"company":"azer","country":"US"},
  {"company":"Sabrina Del Fabbro","country":"IT"},
  {"company":"sofia brem","country":"DE"},
  {"company":"Elena Sokri","country":"GR"},
  {"company":"PALTOGLOU GEORGIOS","country":"GR","city":"DRAMA"},
  {"company":"nancy","country":"BE"},
  {"company":"Samuel Filipe Ribeiro Farelo","country":"PT"},
  {"company":"Ingrid","country":"SK"},
  {"company":"EXTRA S.R.L","country":"IT","city":"PINEROLO","sales":"Vito"},
  {"company":"nel-ood","country":"BG","city":"Burgas","sales":"Veronica"},
  {"company":"Caroline Fechner","country":"DE","city":"Lienen"},
  {"company":"CENTRU MODY HURT DYSTRYBUCJA","country":"PL","city":"Olsztyn","sales":"Veronica"},
  {"company":"MAROSTYLE","country":"FR","city":"AUBERVILLIERS","lat":48.9131,"lng":2.3835,"sales":"Veronica"},
  {"company":"Antonio Andreev","country":"BG"},
  {"company":"NEW JENYFEL S.R.L","country":"RO","city":"BAIA MARE","sales":"Veronica"},
  {"company":"ABRUZZESE S.R.L","country":"IT","city":"LA SPEZIA","sales":"Veronica"},
  {"company":"JUAN TEWERIA UGALDE Y OTRAS C.B","country":"ES","city":"DONOSTIA-SAN SEBASTIAN","sales":"Veronica"},
  {"company":"my Lantadeli 9-11","country":"FR","sales":"Vito"},
  {"company":"MILLENIUM MALGORZATA TARACINSK","country":"PL","sales":"Veronica"},
  {"company":"DESIDERI DI PINNA ROBERTA","country":"IT","city":"MARCIANA","sales":"Veronica"},
  {"company":"nannini Morena","country":"IT"},
  {"company":"Tanasko Bajic","country":"RS"},
  {"company":"STUDIO 34 SNC DI ZANZANI MASSIMO","country":"IT","city":"SAN MAURO PASCOLI","sales":"Vito"},
  {"company":"Cocchi patrizia","country":"IT","city":"TERNI","sales":"Vito"},
  {"company":"C & D S.R.L","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Veronica"},
  {"company":"STEEDELUXE","country":"DE","city":"Lienen","sales":"Vito"},
  {"company":"Virginia Caciolli","country":"IT"},
  {"company":"Maria Maddalena","country":"IT"},
  {"company":"LIAGKOS KONSRANTINOS BAGSTORE","country":"GR","city":"Athens","lat":37.9838,"lng":23.7275,"sales":"Veronica"},
  {"company":"LINEE MODA DI ABIS MAURIZIO","country":"IT","city":"MONSERRATO","sales":"Vito"},
  {"company":"MAGAZINE S.R.L","country":"IT","city":"CAPANNORI","sales":"Vito"},
  {"company":"AFRODITE ARATHYMOY","country":"GR","sales":"Veronica"},
  {"company":"Katie Johnson","country":"IE"},
  {"company":"Maria Monti","country":"IT"},
  {"company":"Овчаренко","country":"RU"},
  {"company":"Sam hou","country":"DZ"},
  {"company":"中希luisa","country":"GR","city":"Thessaloniki","lat":40.6401,"lng":22.9444,"debt":1525.0,"sales":"Livio"},
  {"company":"李科毅 Li min tziyong","country":"GR","city":"Thessaloniki","lat":40.6401,"lng":22.9444,"sales":"Nico"},
  {"company":"RITZI GECOSA S.R.L","country":"RO","city":"BACAU","sales":"Vito"},
  {"company":"DI STEFANO SIMONA","country":"IT","city":"GIULIANOVA","sales":"Veronica"},
  {"company":"Michela Mancinelli","country":"IT"},
  {"company":"MODE IN FASHION Pu","country":"DE","city":"POCKING","sales":"Veronica"},
  {"company":"luana lupaioli","country":"IT"},
  {"company":"sarah falcione","country":"IT"},
  {"company":"Duc Viet","country":"PL"},
  {"company":"REBEL DI STERNINi ANDREA","country":"IT","city":"RAVENNA","sales":"Veronica"},
  {"company":"Alice Sbardolini","country":"IT","city":"LISSONE(MB)"},
  {"company":"FORTE S.R.L.S","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Veronica"},
  {"company":"ZANA S.R.L","country":"IT","city":"GRADO","sales":"Veronica"},
  {"company":"angelica finamore","country":"IT"},
  {"company":"PARDEBRINCOS COMERCIO DE ACESSORIOS DE MODA FEMININA LDA","country":"PT","city":"AMADORA","sales":"Vito"},
  {"company":"MGM S.R.L","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Veronica"},
  {"company":"ROSSALIA ANETA ANTOLAK","country":"PL","sales":"Vito"},
  {"company":"MARCIN","country":"PL"},
  {"company":"MARINA VOGT","country":"DE","sales":"Vito"},
  {"company":"MERVILIO ZBIGNIEW LEWANDOWSKi","country":"PL","sales":"Nico"},
  {"company":"GORILLA DUDE S.R.L.S","country":"IT","city":"PESCANTINA","sales":"Vito"},
  {"company":"S.C.KEOPS FASHION SRL","country":"RO","city":"IASI","sales":"Veronica"},
  {"company":"Muhammad Naveed","country":"GB"},
  {"company":"Paola Genesio","country":"IT"},
  {"company":"KOALA","country":"HR","city":"NOVA GRADIŠKA","sales":"Livio"},
  {"company":"LEGEND d.o.o.","country":"HR","city":"Bjelovar","sales":"Livio"},
  {"company":"IMELDE TILAVERDOU MARIANA","country":"GR","city":"Xanthi","sales":"Veronica"},
  {"company":"F.H.BEATa NIEWRZATEK","country":"PL","sales":"Vito"},
  {"company":"IPG LTD","country":"BG","city":"Varna","sales":"Veronica"},
  {"company":"MEHRAN S.R.L","country":"IT","city":"COMO","sales":"Vito"},
  {"company":"MON.DO.MODA S.A.S DI ANNA ROSARIA MONTEMURRE E C","country":"IT","city":"MATERA","sales":"Vito"},
  {"company":"KELLY BIJOUX DI TURINA TIZIANA","country":"IT","city":"MANTOVA","sales":"Veronica"},
  {"company":"GENESIO PAOLA","country":"IT","city":"FLORIDIA","sales":"Veronica"},
  {"company":"DOMUS ART SRL","country":"IT","city":"SAN SECONDO PARMENSE","sales":"Veronica"},
  {"company":"YLISTARON HALPA-AITTA OY","country":"FI","city":"YLISTARO","sales":"Veronica"},
  {"company":"GRIGIO SABBIA DI FRANCO PACINI","country":"IT","city":"GENOVA","lat":44.4056,"lng":8.9463,"region":"Liguria","sales":"Veronica"},
  {"company":"NITRO BAGS LTD","country":"GR","city":"Athens","lat":37.9838,"lng":23.7275,"sales":"Veronica"},
  {"company":"SPRL SEVEN BAGS","country":"BE","city":"WAREMME"},
  {"company":"massimo rizzato","country":"IT"},
  {"company":"Nati Bismut","country":"IL"},
  {"company":"manuela gokinajew","country":"IT"},
  {"company":"kkLivio","country":"IT","city":"firenze","lat":43.7696,"lng":11.2558,"region":"Toscana"},
  {"company":"EL MIRON 43","country":"ES","city":"PALMAS DE GRAN CANARIA (LAS)"},
  {"company":"Benedetta Golles","country":"IT"},
  {"company":"Jaana Hautamaki","country":"FI"},
  {"company":"Luigi Bellani","country":"IT"},
  {"company":"cinzia Scorcelletti","country":"IT"},
  {"company":"Simona Dumitrescu","country":"RO"},
  {"company":"christian zulian","country":"IT"},
  {"company":"ABIBI DI VANNOZZI SIMONE","country":"IT","city":"FIRENZE","lat":43.7696,"lng":11.2558,"region":"Toscana","sales":"Veronica"},
  {"company":"Zhumakhmet Aigul","country":"KZ"},
  {"company":"beneforti","country":"IT"},
  {"company":"ahmet","country":"TR"},
  {"company":"张his","country":"EG","city":"nxis"},
  {"company":"Semra Mehidic","country":"AT","city":"salzburg"},
  {"company":"ferreri giorgia","country":"IT"},
  {"company":"em","country":"FR"},
  {"company":"maria","country":"SK"},
  {"company":"Catia Antunes","country":"PT"},
  {"company":"Rania Papadimitriou","country":"GR"},
  {"company":"Cristina Marcoci","country":"RO"},
  {"company":"molina","country":"FR"},
  {"company":"Łukasz Nowak","country":"PL"},
  {"company":"Elena Carballo Voces","country":"ES","city":"Ponferrada"},
  {"company":"Spelthahn Nadia","country":"FR"},
  {"company":"alexsandra sedoni","country":"IT"},
  {"company":"José Oliveira","country":"PT"},
  {"company":"david","country":"VE"},
  {"company":"Daniela Vada","country":"IT"},
  {"company":"alessio cantone","country":"IT"},
  {"company":"Milena Bineva","country":"BG"},
  {"company":"Erin Burris","country":"US"},
  {"company":"Zalikha","country":"MY"},
  {"company":"elisa andorlini","country":"IT"},
  {"company":"Muri Rosa Angela","country":"IT"},
  {"company":"Blondel","country":"FR"},
  {"company":"luigi barbato","country":"IT"},
  {"company":"ELENA KALOUTSIKOU","country":"GR"},
  {"company":"BARBARA","country":"IT"},
  {"company":"Laura Falliti","country":"IT"},
  {"company":"elisa urban","country":"IT"},
  {"company":"Dariusz Garbacz","country":"PL"},
  {"company":"Gorit","country":"FR"},
  {"company":"Luigi","country":"IT"},
  {"company":"teresa sulaiman","country":"IT"},
  {"company":"Lucia Faconti","country":"IT"},
  {"company":"Iolanda Romão","country":"PT"},
  {"company":"andro","country":"GR"},
  {"company":"vitor","country":"PT"},
  {"company":"Francisco Peman","country":"ES"},
  {"company":"wang","country":"FR"},
  {"company":"Mafalda Ramos","country":"PT"},
  {"company":"Pablo","country":"ES"},
  {"company":"PAPAGEORGANTA MARIA","country":"GR"},
  {"company":"Nicole Ebner","country":"AT"},
  {"company":"Castellanos","country":"FR"},
  {"company":"Dimitris","country":"GR"},
  {"company":"Puntino","country":"HR"},
  {"company":"李君珍jenny","country":"IT"},
  {"company":"Mario Rossi","country":"IT"},
  {"company":"samanta casta","country":"IT"},
  {"company":"Marina Puga","country":"PT"},
  {"company":"antonino","country":"IT"},
  {"company":"eduard","country":"RO"},
  {"company":"vancayzeele","country":"BE"},
  {"company":"Iris Lazzarini","country":"IT"},
  {"company":"scarpe diem","country":"IT"},
  {"company":"Sara Chelli","country":"HR"},
  {"company":"stefania tanzi","country":"IT"},
  {"company":"Kovács Alexandra","country":"HU"},
  {"company":"luca donati","country":"IT"},
  {"company":"Antonio Vizzi","country":"IT"},
  {"company":"vincent julie","country":"BE"},
  {"company":"youmbi Fomo Herve","country":"IT"},
  {"company":"paolo migliore","country":"IT"},
  {"company":"BOLSOS VALENTINA, S.L","country":"ES","city":"FUENLABRADA"},
  {"company":"MODA FRANCA","country":"IT","city":"NAPOLI","lat":40.8518,"lng":14.2681,"region":"Campania"},
  {"company":"Carmen Perdomo Arvelo","country":"ES"},
  {"company":"zyane rachida","country":"IT"},
  {"company":"youness nhili","country":"IT"},
  {"company":"Ginet sophie","country":"FR"},
  {"company":"laisne","country":"FR"},
  {"company":"Mariangela cardini","country":"IT"},
  {"company":"gatti","country":"FR"},
  {"company":"Tatjana Filipcic Golubic","country":"HR"},
  {"company":"ali","country":"NL"},
  {"company":"christian levrini","country":"IT"},
  {"company":"Marcello Magozzi","country":"IT"},
  {"company":"Fabrizio Caccamo","country":"IT"},
  {"company":"Seto hiroki","country":"IT"},
  {"company":"CHANTES D.o.o.","country":"HR","city":"Rijeka","sales":"Livio"},
  {"company":"flora 马德里","country":"ES","sales":"Nico"},
  {"company":"fabiana bonelli","country":"IT"},
  {"company":"Gianluca","country":"IT"},
  {"company":"INTERNESHANAL DEVELOPMENT - OOD","country":"BG","city":"SOFIYA"},
  {"company":"DI EN SI 62 - EOOD","country":"BG","city":"Dobrich"},
  {"company":"MILANO COLLECTION SRL","country":"RO","city":"BUCURESTI, SECTOR 2"},
  {"company":"chloe gelle","country":"FR"},
  {"company":"saurel","country":"FR"},
  {"company":"Aziza Merbouh","country":"IT"},
  {"company":"Gisela Abreu","country":"PT"},
  {"company":"Andrea Galvani","country":"IT"},
  {"company":"murray leihn","country":"AU"},
  {"company":"kaia","country":"SK"},
  {"company":"Sara mazzoli","country":"IT"},
  {"company":"Miriana Maria Buffa","country":"IT"},
  {"company":"Prima Fila Shop","country":"IT"},
  {"company":"P.P.H.U EL-BIM JAROSLAM LEONHARDT","country":"PL","city":"Lublin"},
  {"company":"sara","country":"IT"},
  {"company":"MEA","country":"FR"},
  {"company":"di stasi","country":"IT"},
  {"company":"BOUTIQUE MODA & SZYK","country":"PL","city":"Białystok","sales":"Livio"},
  {"company":"Rosa Girgenti","country":"IT"},
  {"company":"ettire","country":"IT"},
  {"company":"Chanel","country":"BE"},
  {"company":"625335619","country":"ES"},
  {"company":"0688305021","country":"FR"},
  {"company":"Federica Stella","country":"IT"},
  {"company":"Stefano Spadini","country":"IT"},
  {"company":"Kimberly","country":"BE"},
  {"company":"Joaquim Tavares","country":"PT"},
  {"company":"Melide Temiz Sahin","country":"BE"},
  {"company":"Virginie Pietri","country":"FR"},
  {"company":"garcia","country":"FR"},
  {"company":"Patrícia Dias","country":"PT"},
  {"company":"ana lopez cuerdo","country":"ES"},
  {"company":"Monika Norkienė","country":"LT"},
  {"company":"Gass 5 doo","country":"SI","sales":"Livio"},
  {"company":"eliseo vitalizio","country":"IT"},
  {"company":"martin","country":"FR"},
  {"company":"giuseppe  Lamberti","country":"IT"},
  {"company":"greta piavani","country":"IT"},
  {"company":"ettori caroline","country":"FR"},
  {"company":"Charline","country":"BE"},
  {"company":"Monique","country":"NL"},
  {"company":"jlenia papini","country":"IT"},
  {"company":"Pietro","country":"SE"},
  {"company":"Georgiana","country":"GB"},
  {"company":"Giovanni Giugliano","country":"IT"},
  {"company":"andrea zingarello","country":"IT"},
  {"company":"rafaela","country":"PT"},
  {"company":"verniero antonio","country":"IT"},
  {"company":"THS ILIOUPOLI e.e","country":"GR"},
  {"company":"THS STORE SS","country":"GR","city":"Kallithga Athens","sales":"Nico"},
  {"company":"lucia mangiameli","country":"IT"},
  {"company":"Larraitz Olias San Sebastian","country":"ES"},
  {"company":"Hugo Correia","country":"PT"},
  {"company":"Laura Šidagienė","country":"LT"},
  {"company":"ALLORA MODA","country":"SK"},
  {"company":"attalah Karim","country":"FR"},
  {"company":"cristina quintana trulock","country":"ES"},
  {"company":"ROMAN HABERMANN","country":"DE","city":"MUNICH GERMANY"},
  {"company":"Alberto nonnis","country":"IT"},
  {"company":"donovan","country":"US"},
  {"company":"Laurelyne","country":"FR"},
  {"company":"Davide/Logrippo","country":"IT"},
  {"company":"Nicole Zanda","country":"IT"},
  {"company":"annaka","country":"BE"},
  {"company":"Levieux","country":"FR"},
  {"company":"Dubuche Laetitia","country":"FR"},
  {"company":"Tereza Krizkova","country":"CZ"},
  {"company":"Tendencia Cadaval","country":"PT"},
  {"company":"Ana Soares","country":"PT"},
  {"company":"Debbie de Haer","country":"NL"},
  {"company":"Louis Brachet","country":"FR"},
  {"company":"Marcin Biskupek","country":"PL"},
  {"company":"Brunetti Alessia","country":"IT"},
  {"company":"Raquel","country":"PT"},
  {"company":"eleni kostopoulou","country":"GR"},
  {"company":"MB07","country":"IT","city":"FORLI'","sales":"Livio"},
  {"company":"ANA MARTINEZ GADEA","country":"ES"},
  {"company":"Alexandra Mpampala","country":"GR"},
  {"company":"SpringSTAR","country":"FR"},
  {"company":"Elodie Demazière","country":"CH"},
  {"company":"manuela gay tejea","country":"ES"},
  {"company":"gaia oliviero","country":"IT"},
  {"company":"Lucrezia Spinella","country":"IT"},
  {"company":"Chelli","country":"DZ"},
  {"company":"fabio millemaci","country":"IT"},
  {"company":"Maria Ángeles Darías Cubas","country":"ES"},
  {"company":"roberto.pallada@gmail.com","country":"IT"},
  {"company":"djo fashion","country":"DZ"},
  {"company":"Bianka Burcakova","country":"SK"},
  {"company":"mandy","country":"NL"},
  {"company":"c","country":"IT"},
  {"company":"\"TUTTO BENE\" COMPANY KFT","country":"HU","city":"HUNGARY"},
  {"company":"Veljas d.o.o.","country":"HR","city":"Zegred","sales":"Nico"},
  {"company":"susana martins","country":"PT"},
  {"company":"Sara Filipa","country":"PT"},
  {"company":"filippo derio cona","country":"IT"},
  {"company":"Marta Mota","country":"PT"},
  {"company":"ester masci","country":"IT"},
  {"company":"Maria Armanda Tribuzi","country":"IT"},
  {"company":"Germano Sa","country":"PT"},
  {"company":"Millionaire by Millionaire sas di Tacchio Paolo & c.","country":"IT"},
  {"company":"Paula Simoes","country":"PT"},
  {"company":"Manuela Marchetto","country":"IT"},
  {"company":"annita","country":"IT"},
  {"company":"Soraya Van Cauwenberghe","country":"BE"},
  {"company":"pel","country":"FR"},
  {"company":"jouan","country":"FR"},
  {"company":"Walter Licastro","country":"IT"},
  {"company":"Letara Giles","country":"US"},
  {"company":"Milan","country":"SK"},
  {"company":"Veneta Pishmanova","country":"BG"},
  {"company":"Shopping Privé","country":"FR"},
  {"company":"gatta mario","country":"BE"},
  {"company":"rosanna","country":"IT"},
  {"company":"mathieu","country":"FR"},
  {"company":"CATALANO GMBH & co","country":"DE","city":"Sindelfingen","sales":"Livio"},
  {"company":"SARL MILANA-LEA VALENTINA","country":"FR","city":"LYON-FRANCE"},
  {"company":"卢春月 LUNA DI LU CHUNYUE","country":"IT","city":"CASAMASSIMA","sales":"Veronica"},
  {"company":"TRADIZIONE MODA SRL","country":"IT","city":"PAESE"},
  {"company":"Prime fashion srl","country":"IT","city":"TREZZO SULL ADDA","sales":"Vito"},
  {"company":"CRUMINA D.O.O.","country":"HU","city":"PAKRAC"},
  {"company":"Catalano beteiligungs gmbh","country":"AT","sales":"Vito"},
  {"company":"Manuela José Calado Fortunato","country":"PT"},
  {"company":"KURT KOLLN GMBH","country":"DE","city":"HAMBURG GERMANY"},
  {"company":"Rui silva","country":"PT"},
  {"company":"GAYA srl","country":"IT","city":"Giugliano","sales":"Nico"},
  {"company":"Daniela Vieira da Costa","country":"PT"},
  {"company":"milan lakostik","country":"SK","sales":"Livio"},
  {"company":"Catarina Salazar","country":"PT"},
  {"company":"COMERCIAL PEZ LTDA","country":"CL","city":"SANTIAGO CILE"},
  {"company":"SEVILLA SYLWIA GRUCHEL","country":"PL","city":"JAWORZE"},
  {"company":"Luca Caschili","country":"IT"},
  {"company":"BORZON ANDRAS","country":"HU","sales":"Livio"},
  {"company":"HUAHAO","country":"GR","city":"THESSALONIKI","lat":40.6401,"lng":22.9444,"sales":"Livio"},
  {"company":"s.c. ALTAMIRA MODA SRL","country":"RO","city":"cluj napoca","sales":"Livio"},
  {"company":"BAHOU","country":"FR"},
  {"company":"miriam idilli","country":"IT"},
  {"company":"Daniela Marques","country":"PT"},
  {"company":"sara mascelluti","country":"IT"},
  {"company":"Melissa Sias","country":"IT"},
  {"company":"morrettini marco","country":"IT"},
  {"company":"Charlotte Donadjian","country":"FR"},
  {"company":"Victor Mato Gañete","country":"ES"},
  {"company":"we fix you","country":"IT"},
  {"company":"Eleni  Papachristou","country":"GR"},
  {"company":"Susana Carapuça","country":"PT"},
  {"company":"Paola Sabatini","country":"IT"},
  {"company":"Michaela Rožičová","country":"CZ"},
  {"company":"Adrián Costa Trillo","country":"ES"},
  {"company":"Céline Hélèna Sacha","country":"BE"},
  {"company":"等级不好urrutia","country":"FR"},
  {"company":"永西 larosa","country":"IT","city":"Catania","lat":37.5079,"lng":15.083,"region":"Sicilia","sales":"Veronica"},
  {"company":"Ana Silva","country":"PT"},
  {"company":"DOLLIBAG","country":"FR","sales":"Livio"},
  {"company":"Myrsini","country":"GR"},
  {"company":"Myrsini Moutzouri","country":"GR"},
  {"company":"coco","country":"HR"},
  {"company":"喬雷","country":"TW"},
  {"company":"Sunajna Acharju","country":"NL"},
  {"company":"nucci","country":"IT"},
  {"company":"So Glam","country":"IT"},
  {"company":"OLIVIA","country":"PT"},
  {"company":"Antoaneta Pavlova","country":"BG"},
  {"company":"Luana Marangia","country":"IT"},
  {"company":"esseqi srl","country":"IT","city":"BORGETTO","sales":"Livio"},
  {"company":"Vladimir","country":"RS"},
  {"company":"Stefania","country":"IT"},
  {"company":"Ettore Ferrara","country":"IT"},
  {"company":"BIMBA E.E","country":"GR","city":"NEA IONIA ATHENS"},
  {"company":"rumiej","country":"FR"},
  {"company":"ordo invest","country":"HU"},
  {"company":"serena","country":"IT"},
  {"company":"hGiuseppe","country":"IT"},
  {"company":"sochova","country":"SK"},
  {"company":"sanne","country":"DK"},
  {"company":"claudia colombo","country":"IT"},
  {"company":"Salma","country":"NL"},
  {"company":"Stephanie glas","country":"NL"},
  {"company":"Ileana Pennucci","country":"IT"},
  {"company":"el uahabi Fonseca","country":"FR"},
  {"company":"Luís boieito","country":"PT"},
  {"company":"MYSTORE SRL corABC","country":"IT","city":"CURNO"},
  {"company":"Giuseppe Spadaro","country":"IT"},
  {"company":"isabelle otten","country":"BE"},
  {"company":"FANTASY BIS S.L.","country":"ES","city":"FUENLABRADA MADRID","lat":40.2842,"lng":-3.7942},
  {"company":"wenyan hong","country":"GF"},
  {"company":"demaeyer","country":"CH"},
  {"company":"Vittoria","country":"IT"},
  {"company":"dewolf","country":"BE"},
  {"company":"zanett","country":"SK"},
  {"company":"Sonia","country":"IT"},
  {"company":"nico","country":"IT"},
  {"company":"antonella gattuso","country":"IT"},
  {"company":"Ana Barbosa","country":"PT"},
  {"company":"Panagiota","country":"GR"},
  {"company":"Nikolina","country":"BA"},
  {"company":"Dea Dea","country":"SI"},
  {"company":"DASTRA. s r.o.","country":"SK","city":"Vinosady Slovensko"},
  {"company":"MC test","country":"US"},
  {"company":"VIANELLO ITALIAN LIFESTYLE","country":"AT","city":"TECHELSBERG"},
  {"company":"Anastasiou Vasiliki Filippos","country":"GR","sales":"Nico"},
  {"company":"GINO/FERRA GROUP","country":"IT","city":"MODICA","sales":"Livio"},
  {"company":"Sirkon s.a","country":"GR","city":"Metamorfossi Athens"},
  {"company":"GINO/GISCAL","country":"IT","sales":"Livio"},
  {"company":"GINO/LA PERLA","country":"IT","city":"MISTERBIANCO CT","sales":"Livio"},
  {"company":"GINO/LEONE","country":"IT","city":"PALERMO","lat":38.1157,"lng":13.3613,"region":"Sicilia","sales":"Livio"},
  {"company":"GINO/CENTRO MEGA","country":"IT","city":"palermo","lat":38.1157,"lng":13.3613,"region":"Sicilia","sales":"Livio"},
  {"company":"GINO/MAURI SRL","country":"IT","city":"MESSINA","sales":"Livio"},
  {"company":"ZHONG SHAN HU YUNZAI ZHI YU","country":"GR","city":"Athena","lat":37.9838,"lng":23.7275},
  {"company":"超 JIN CAI PING SHU MEI","country":"GR","city":"ATHENA","lat":37.9838,"lng":23.7275,"sales":"Veronica"},
  {"company":"EVA CERVENA BORSE DESIGN","country":"CZ","city":"PROSTEJOV-REPUBBLICA CECA"},
  {"company":"SARL NEW WAVE BAGS","country":"FR","city":"AUBERVILLIERS","lat":48.9131,"lng":2.3835},
  {"company":"TRETTER JOSEF GMBH&CO;.KG","country":"MA","city":"Munchen","lat":48.1351,"lng":11.582},
  {"company":"VANTO 9 SRL Vivian","country":"IT","sales":"Nico"},
  {"company":"新奇迹","country":"PT","city":"Fajozes Portogallo","sales":"Nico"},
  {"company":"Johan Olausson","country":"SE"},
  {"company":"Nicola Ventura","country":"GR"},
  {"company":"Sissi schilo jolie","country":"FR","city":"aubervilliers","lat":48.9131,"lng":2.3835},
  {"company":"Duong","country":"SK"},
  {"company":"GSQUARE SRL","country":"IT","city":"torino","lat":45.0703,"lng":7.6869,"region":"Piemonte","sales":"Livio"},
  {"company":"FLORENCE BAGS SRL","country":"IT","sales":"Livio"},
  {"company":"Gianluca Russo","country":"IT"},
  {"company":"valentina","country":"IT","city":"Perugia"},
  {"company":"Elisa00","country":"IT"},
  {"company":"livio","country":"IT"},
  {"company":"W101 MAI THEN VAN KFT","country":"UY","city":"Budapest","lat":47.4979,"lng":19.0402},
  {"company":"慧子 IFA","country":"AT","city":"WIEN","lat":48.2082,"lng":16.3738},
  {"company":"MOHAMMAD SHAHRAZ","country":"FR"},
  {"company":"NICE FASHION","country":"FR","city":"MARSEILLE","lat":43.2965,"lng":5.3698},
  {"company":"ETA PINK","country":"IT","city":"Firenze","lat":43.7696,"lng":11.2558,"region":"Toscana"},
  {"company":"Sdegno Marina","country":"IT","city":"Portici"},
  {"company":"xinxin jin","country":"IT","city":"sesto fiorentino"},
  {"company":"散 viviana","country":"IT","city":"cagliari","lat":39.2238,"lng":9.1217,"region":"Sardegna"},
  {"company":"NEW J&J Di ZHOU GUO HUA SAS","country":"IT","city":"CAGLIARI","lat":39.2238,"lng":9.1217,"region":"Sardegna","sales":"Veronica"},
  {"company":"Maru’tamburo","country":"IT","city":"CERIGNOLA","sales":"Livio"},
  {"company":"CO&CO;","country":"GR","city":"Thessaloniki","lat":40.6401,"lng":22.9444},
  {"company":"ET.RRGO KONSTANTIN","country":"BG","sales":"Livio"},
  {"company":"VENTIA SKAPI","country":"GR","sales":"Livio"},
  {"company":"SC FREE GAIR SRL","country":"RO","city":"Timisoara"},
  {"company":"DYNAMIC MIRACLE UNIPESSOAL LDA","country":"PT","city":"VILA DO CONDE","lat":41.3525,"lng":-8.7426},
  {"company":"Afonso pereira","country":"BG","city":"Lisboa","lat":38.7223,"lng":-9.1393,"sales":"Nico"},
  {"company":"MONEGON SIMONE","country":"IT","city":"LAINATE"},
  {"company":"小莲Budapest","country":"HU"},
  {"company":"LA MAISON SRL","country":"IT","city":"ROMA","lat":41.9028,"lng":12.4964,"region":"Lazio","sales":"Livio"},
  {"company":"ZHANG JUNYU","country":"GR","city":"THESSALONIKI","lat":40.6401,"lng":22.9444},
  {"company":"建波MI","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia","sales":"Veronica"},
  {"company":"LIANCHUN HONG SL","country":"SL","city":"MADRID ESPANA"},
  {"company":"HU YUNZAI","country":"GR","city":"Athena","lat":37.9838,"lng":23.7275,"sales":"Nico"},
  {"company":"MASSIMO BOLSOS SL","country":"ES","city":"MALAGA"},
  {"company":"Bolsos Xane","country":"ES","city":"Elche Alicante","sales":"Nico"},
  {"company":"Total Collection","country":"RO","city":"Bucuresti","lat":44.4268,"lng":26.1025,"sales":"Nico"},
  {"company":"Jessy佳琪","country":"GR","city":"Athens","lat":37.9838,"lng":23.7275,"sales":"Nico"},
  {"company":"小莲","country":"UY"},
  {"company":"黄家皮具","country":"ES","city":"magala","sales":"Livio"},
  {"company":"ERRE DE RASO S.L.","country":"ES","city":"BARCELONA","lat":41.3851,"lng":2.1734},
  {"company":"SAS MOUCHET BURY","country":"FR","city":"Vauvert","sales":"Nico"},
  {"company":"郑英强","country":"PT","city":"Lisboa","lat":38.7223,"lng":-9.1393,"sales":"Veronica"},
  {"company":"广昌集团 GUANGCHANG SLR","country":"ES","city":"巴塞罗那 BARCELONA"},
  {"company":"SARA BOLSOS","country":"ES","city":"FUENLABRADA MADRID","lat":40.2842,"lng":-3.7942},
  {"company":"B.B RETAIL S.R.L","country":"IT","city":"NAPOLI","lat":40.8518,"lng":14.2681,"region":"Campania"},
  {"company":"Sarl la Sapotille","country":"FR","city":"Nantes","sales":"Nico"},
  {"company":"TANARA KRT","country":"HU","city":"BUDAPEST","lat":47.4979,"lng":19.0402,"sales":"Veronica"},
  {"company":"POLY IMPORT & EXPORT","country":"DE","city":"DREIEICH","lat":50.0236,"lng":8.7},
  {"company":"TOP TWO MADE & LEDER GMBH","country":"DE","city":"BERLIN","lat":52.52,"lng":13.405},
  {"company":"S.AVRAMIDS","country":"GR"},
  {"company":"Florence corporation","country":"JP","city":"Nouninbashi chuo ku Osaka","sales":"Nico"},
  {"company":"NATI BISMUT FAVORITE","country":"IL","city":"PARDES - HANA.ISRAEL"},
  {"company":"Nexus shoes srl","country":"RO","city":"Sect 1 bucanest","sales":"Nico"},
  {"company":"STRASS & STRASS SRL","country":"IT","city":"FUNO DI ARGELATO","lat":44.6333,"lng":11.35,"region":"Emilia-Romagna"},
  {"company":"LOOKAT SARL L'OCEAN","country":"FR","city":"AUBERVILLIERS","lat":48.9131,"lng":2.3835},
  {"company":"SARL F.A.B DESIGN","country":"FR","city":"PARIS-FRANCE"},
  {"company":"Pantelis alexandros","country":"GR","city":"Thesaloniki","sales":"Nico"},
  {"company":"SARL kL","country":"FR","city":"Aubervillers"},
  {"company":"VOF WILLAERT","country":"BE","city":"BELGIUM"},
  {"company":"Melgamon","country":"ES","city":"Salou madrid"},
  {"company":"KRESO PROMET D.O.O","country":"HR","city":"ZADAR HRVATSKA"},
  {"company":"Cloiver Bag","country":"ES","city":"Barcelona","lat":41.3851,"lng":2.1734},
  {"company":"荣华 AMICA MODA","country":"IT","city":"Brescia","lat":45.5416,"lng":10.2118,"region":"Lombardia"},
  {"company":"ONLY STYLE DI PUTIGNANO GAETANO","country":"AT","city":"villach"},
  {"company":"GO MODE SPRL","country":"BE","city":"EUGIES-B"},
  {"company":"AUREN SAS EURO LINE","country":"FR","city":"EPINAY SUR SEINE"},
  {"company":"LING ZHAO","country":"GR","city":"atene"},
  {"company":"建新 Easy Day","country":"FR","city":"AUBERVILLIERS","lat":48.9131,"lng":2.3835},
  {"company":"Sc Forseti Master Srl","country":"RO"},
  {"company":"VELIVASAKIS M.-VELIVASAKI AIK.&SIA o.e.","country":"GR","city":"ATHENS","lat":37.9838,"lng":23.7275},
  {"company":"NEWSAN","country":"IT","city":"NAPOLI","lat":40.8518,"lng":14.2681,"region":"Campania"},
  {"company":"NI XIAOFEN XIUZHAI","country":"GR","city":"Athens","lat":37.9838,"lng":23.7275},
  {"company":"SARL SARL CATOE","country":"FR","city":"SAINT-NAZAIRE"},
  {"company":"AYA SRL","country":"IT","city":"Prato","lat":43.8777,"lng":11.0955,"region":"Toscana","sales":"Veronica"},
  {"company":"吴晓珍 HUA DA GMBH","country":"DE","city":"Neuss","lat":51.198,"lng":6.6917},
  {"company":"陈镁","country":"HU"},
  {"company":"COVENTUR AFNIESZKA JANISZEWSKA","country":"PL","city":"Bienewice"},
  {"company":"MAR MEDIACA D.O.O","country":"SI","city":"KRSKO SLOVENIJA"},
  {"company":"DOWNSON VIZIA LTD","country":"BG"},
  {"company":"FA. SUN KAIXI","country":"AT","city":"Wien","lat":48.2082,"lng":16.3738},
  {"company":"VICTORY ENTERTAINMENT S.A","country":"GR","city":"Gerakas Attica-Greece","sales":"Veronica"},
  {"company":"CONSTANT BAGS SMPC","country":"GR","city":"Athens","lat":37.9838,"lng":23.7275},
  {"company":"OMIKRON CHAPADO S.L.","country":"ES","city":"Cambrils"},
  {"company":"邱增陆 MALAS ANGELA","country":"PT","city":"Vila Do Conde","lat":41.3525,"lng":-8.7426,"sales":"Veronica"},
  {"company":"WU XINYI MINSONG","country":"GR","city":"Athena","lat":37.9838,"lng":23.7275,"sales":"Veronica"},
  {"company":"FELIRAM SRL","country":"RO"},
  {"company":"MINI BOUTIQUE SRL","country":"RO","city":"Sat. Stefanestii de jos ilfov"},
  {"company":"LA FESTIN BOLSOS","country":"ES","city":"ALICANTE"},
  {"company":"Lookici Ayyoub","country":"FR","city":"Narbonne"},
  {"company":"EXPORT","country":"ES","city":"Elche Alicante"},
  {"company":"Maylander emese Gabriella","country":"HU","city":"Bekescsaba"},
  {"company":"Gianna shoes doo","country":"HR","city":"Zagreb","lat":45.815,"lng":15.9819},
  {"company":"Petra ind andreas struck gbr","country":"DE","city":"Greifswald"},
  {"company":"D&T Morava s.r.o.","country":"CZ","city":"627 00 brno 27","sales":"Veronica"},
  {"company":"FIMAR","country":"IT","city":"Piazzolla di Nola"},
  {"company":"LILINGZHI TOU YOXIN","country":"GR","city":"Athens","lat":37.9838,"lng":23.7275},
  {"company":"KIMIWITT2014 S.L. VENTA POR MAYOR","country":"ES","city":"MADRID","lat":40.4168,"lng":-3.7038},
  {"company":"ANDREA BORSE S.A.S DI ZHOU CHUNYUE&C.","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia"},
  {"company":"F.H.U MARDER MAREK TOMASZEWSKI","country":"PL","city":"SZAMOTULY"},
  {"company":"KOUAEI E.COM -TIU","country":"HU"},
  {"company":"DAYMEN TEX","country":"FR","city":"AUBERVILLIERS","lat":48.9131,"lng":2.3835},
  {"company":"GIADA","country":"BE"},
  {"company":"JIAJING GMBH","country":"DE","city":"Dreieich","lat":50.0236,"lng":8.7},
  {"company":"MARNIK LTD","country":"CY","city":"Limassol"},
  {"company":"MIRELLA SRL","country":"IT","city":"Trieste"},
  {"company":"ANGELA DI CHEN SHAOMEI","country":"IT","city":"Napoli","lat":40.8518,"lng":14.2681,"region":"Campania"},
  {"company":"中国城","country":"GR","city":"Thessalonici"},
  {"company":"子明","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia"},
  {"company":"海华","country":"IT","city":"Milano","lat":45.4642,"lng":9.19,"region":"Lombardia"},
  {"company":"HU YUN QU","country":"GR","city":"ATHENA","lat":37.9838,"lng":23.7275,"sales":"Veronica"},
  {"company":"DESIGNER PLUS TOMASZ","country":"PL","sales":"Veronica"},
  {"company":"ELECCIO BELLA S.L.U","country":"ES","city":"Sant Adria se besos Barcelona"},
  {"company":"RANKINE SRL","country":"RO","city":"Timisoara"},
  {"company":"CITY BAG GMBH","country":"CH","city":"Othmarsingen"},
  {"company":"MARIA INGROSSO BORSE E ACCESORI","country":"IT","city":"Bari","lat":41.1171,"lng":16.8719,"region":"Puglia","sales":"Veronica"},
  {"company":"SKY FLAME GMBH","country":"DE","city":"NEUSS","lat":51.198,"lng":6.6917},
  {"company":"MIR-EOOD SUNAY MEHMED","country":"BG","city":"Haskovo"},
  {"company":"WOW MODE EXKLUSIV","country":"DE","city":"Sinsheim"},
  {"company":"XY","country":"HU","city":"BUDAPEST","lat":47.4979,"lng":19.0402},
  {"company":"COCCO FERNANDO SRL","country":"IT","city":"Citta sant'Angelo","sales":"Veronica"},
  {"company":"MASSIMOMILANO S.R.O.","country":"CZ","city":"Jesenice Praha"},
  {"company":"VASILEIOU MARGARITA","country":"GR","city":"VEROIA","sales":"Veronica"},
  {"company":"MAXIHIT S.R.O","country":"CZ","city":"Pisek","sales":"Veronica"},
  {"company":"MAMET","country":"DZ","sales":"Veronica"},
  {"company":"CONVENTUR AFNIESZKA JANISZEWSKA","country":"PL","city":"Bieniewice"},
  {"company":"ARTIMA SIA","country":"LV","city":"RIGA"},
  {"company":"PEPITA PIOTR JAKUBOWSKI","country":"PL"},
  {"company":"CALZANED","country":"PT","city":"RIO MAIOR - PORTUGAL"},
  {"company":"KORBITEK KER. ES SZOLG KFT","country":"HU","city":"BUDAPEST","lat":47.4979,"lng":19.0402},
  {"company":"COLWBEI SRL","country":"IT","city":"ROMA","lat":41.9028,"lng":12.4964,"region":"Lazio"},
  {"company":"SHOPPING CREATIVO DI TERESA MONTELLA","country":"IT","city":"GROSSETO"},
  {"company":"SHOW TIME LTD","country":"IL","city":"TEL AVIV ISRAEL"},
  {"company":"NEW SAN","country":"IT","city":"NAPOLI","lat":40.8518,"lng":14.2681,"region":"Campania"},
  {"company":"RADICAR BOND KFT","country":"HU","city":"BUDAPEST","lat":47.4979,"lng":19.0402},
  {"company":"VERGO S.R.L","country":"IT","city":"CAMPODARSEGO PADOVA"},
  {"company":"BART S MANKTHANDEL","country":"NL","city":"AMSTENCLAM"},
  {"company":"DONG WEN ZAN 秋林","country":"IT","city":"LECCE"},
  {"company":"啊敬","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia","sales":"Veronica"},
  {"company":"TEDALDA","country":"IT","city":"NOCETO"},
  {"company":"BEUREL PIERRE","country":"FR","city":"LOIX"},
  {"company":"FRANCESCO UBERTI","country":"IT","city":"TRESANA (MS)"},
  {"company":"建波BS","country":"IT","city":"BRESCIA","lat":45.5416,"lng":10.2118,"region":"Lombardia","sales":"Veronica"},
  {"company":"ZAZA MICHELE","country":"IT"},
  {"company":"SALE MILANO","country":"FR","sales":"Veronica"},
  {"company":"胡佳丹","country":"ES","city":"VALENCIA","lat":39.4699,"lng":-0.3763},
  {"company":"PACHYGIANNAKIS EMMANOUIL","country":"GR","city":"MALIA","sales":"Veronica"},
  {"company":"KRISTOFORO","country":"PL","sales":"Veronica"},
  {"company":"REVYU FESHAN","country":"BG","city":"BANKYA","sales":"Veronica"},
  {"company":"KLEO SRL","country":"IT","city":"TREVISO","sales":"Veronica"},
  {"company":"VALENTINA GMBH","country":"DE","city":"NEUSS","lat":51.198,"lng":6.6917},
  {"company":"张国程 SARL CAPRICE","country":"FR","city":"AUBRVILLIERS"},
  {"company":"WANGBAG","country":"FR","city":"AUBERVILLIERS","lat":48.9131,"lng":2.3835},
  {"company":"GECOINT MEDITERRANEO","country":"ES","city":"ALICANTE","sales":"Veronica"},
  {"company":"SHILO JOILE BOLSOS","country":"ES","city":"FUENLABRADA MADRID","lat":40.2842,"lng":-3.7942,"sales":"Veronica"},
  {"company":"DERUNSUN S.L","country":"ES","city":"BARCELONA","lat":41.3851,"lng":2.1734},
  {"company":"林国荣 ANGOLO MODA DI YUAN JI WEN","country":"IT","city":"NAPOLI","lat":40.8518,"lng":14.2681,"region":"Campania","sales":"Veronica"},
  {"company":"SARL LVDI","country":"FR","city":"TREMBLAY"},
  {"company":"张一刀 华丽","country":"GR","city":"THESALONIKH"},
  {"company":"NATASCIA PELLETTERIA","country":"HU","city":"Budapest","lat":47.4979,"lng":19.0402},
  {"company":"MAGHARIKY TRADING S.A.","country":"LB","city":"BELRUT"},
  {"company":"TOP FASHION 88 S.L","country":"ES","city":"MADRID","lat":40.4168,"lng":-3.7038},
  {"company":"SWEET BEAN - SCHNETZER ZHAO","country":"AT","city":"BREGENZ"},
  {"company":"ALEXANDROS DIAVATIS","country":"GR","city":"THESSALONIKI","lat":40.6401,"lng":22.9444},
  {"company":"SAMPSONIDOU DESP EFSTATHIOS","country":"GR","city":"GREECE"},
  {"company":"SANYU SRL","country":"IT","city":"VERONA","lat":45.4384,"lng":10.9916,"region":"Veneto"},
  {"company":"RUGGIERO CROCETTA","country":"IT","city":"NICHELINO"},
  {"company":"CENTRO BORSE SRL","country":"IT","city":"MILANO","lat":45.4642,"lng":9.19,"region":"Lombardia"},
  {"company":"ELLEGI S.R.L.","country":"IT","city":"Genova","lat":44.4056,"lng":8.9463,"region":"Liguria"},
  {"company":"TOP-TEN SAS DI MICHELETTI LUCIANO E ROBERTO &C.","country":"IT","city":"FERRARA"},
  {"company":"CASA SANSHENG S.L","country":"ES","city":"BARDALONA"},
  {"company":"C S G YE SHUSHU CHUNGCHUN","country":"GR","city":"ATHINA"},
  {"company":"INATEL - EOOD","country":"BG","city":".PLOVDIV"},
  {"company":"PRZEDSIEBIORSTWO PRODUKCY","country":"NI","city":"CHELM"},
  {"company":"ELEGANZA EOOD","country":"BG","city":"BULGARIA-VARNA"},
  {"company":"QUINTA STRADA SRL","country":"RO","city":"BUCAREST"},
  {"company":"S.C. BEAUTIFUL S.R.L.","country":"RO","city":"IASI, STR"},
  {"company":"HABETLER ZOLTAN","country":"HU","city":"HUNGARY"},
  {"company":"COLLANDE - BOGDAHN OHG","country":"DE","city":"Hamburg","lat":53.5511,"lng":9.9937},
  {"company":"KANUBA GMBH","country":"CH","city":"GLATTPARK OPFIKEN"},
  {"company":"S.C.ROMBRAC SRL","country":"RO","city":"GALATI ROMANIA"},
  {"company":"MATTEO CROCETTA","country":"IT","city":"Moncalieri"},
  {"company":"THS PRIVATE COMPANY","country":"GR","city":"METAMORFOSIS ATHENE GREECE"},
  {"company":"HIPER - BOLSOS","country":"ES","city":"MALAGA"},
  {"company":"S.A.R.L SAC D'ANGE","country":"FR","city":"LYON -FRANCE"},
  {"company":"SAS LAURA","country":"FR","city":"LYON","lat":45.764,"lng":4.8357},
  {"company":"AKUSTIKA GROUP D.O.O.","country":"SI","city":"LJUBLJANA"},
  {"company":"L&B LEDERWELT GMBH","country":"DE","city":"LENGENFELD"},
  {"company":"LOVELY LAURI ADRIAN RUILE","country":"DE","city":"KONIGSBRUN"},
  {"company":"VOGA MADE IN ITALY","country":"AT","city":"KLAGENFURT"},
  {"company":"DAVAMAL COMSERVICE SRL","country":"RO","city":"J20/1128/1992"},
  {"company":"ELIZA - 2005 - EOOD","country":"BG","city":"PLOVDIV BULGARIA"},
  {"company":"ADL ADVANTAGE DEVELOPMENT & LAUNCHING LTD","country":"BG","city":"PLOVDIV"},
  {"company":"KEWECHRIS","country":"FR","city":"PARIS","lat":48.8566,"lng":2.3522},
  {"company":"TRIS SIL VERTIRIS S.L.","country":"ES","city":"PALENCIA"},
  {"company":"BATTISTUTTA SRL","country":"IT","city":"Novedrate"},
  {"company":"KOCISKY PETER","country":"SK","city":"NOVE ZAMKY SLOVAKKIA"},
  {"company":"KARDAS GMBH","country":"DE","city":"NEUSS","lat":51.198,"lng":6.6917},
  {"company":"LIDA","country":"DE","city":"NEUSS","lat":51.198,"lng":6.6917},
  {"company":"GLOBAL EXPANSION QUEENS, SL","country":"ES","city":"MUTXAMEL - Alicante"},
  {"company":"CIPELE D.O.O.","country":"HR","city":"SPLIT","lat":43.5081,"lng":16.4402},
  {"company":"麦包包JIN CHANG ORIENTAL .S.L.","country":"ES","city":"SEVILLA ESPANA"},
  {"company":"FEDERIKA BAGS,S.L.","country":"ES","city":"SANT ADRA DE BESOS BARCELONA-España"},
  {"company":"CLUCA","country":"NL","city":"SAASVELD"},
  {"company":"KOSKINAS DIMITR NIKOLAOS","country":"GR","city":"RODOS"},
  {"company":"LEDER REUTTER GMBH","country":"DE","city":"REUTIINGEN"},
  {"company":"LE CHAPEAU MARIANNE SCHOEMAN","country":"NL","city":"RD VEENENDAAL"},
  {"company":"SAKWA S.C.JAROSLAW ANTKOWIAK,BEATA ANTKOWIAK","country":"PL","city":"POZNAN"},
  {"company":"\"DORA\" DOROTA ZIMNY","country":"PL","city":"POLONIA"},
  {"company":"AMO DIZAJN JJ D.O.O.","country":"HR","city":"ZAGREB-SLOBOSTINA"},
  {"company":"FA.EUROBAGS E.U.","country":"AT","city":"WIEN","lat":48.2082,"lng":16.3738},
  {"company":"MODA SERVER - ACESSORIOS MODA ,LDA","country":"PT","city":"VILA DO CONDE","lat":41.3525,"lng":-8.7426},
  {"company":"KARA Trutnov, a.s.","country":"CZ","city":"TRUTNOV"},
  {"company":"NILS SAFSTROM AB","country":"SE","city":"TROSA-SWEDEN"},
  {"company":"XIN ZHONG HUA CHEN HUAMEI","country":"GR","city":"THESSALONIKI-GREECE"},
  {"company":"AVRAAM SPYROPOULOS & CO OE","country":"GR","city":"THESSALONIKI","lat":40.6401,"lng":22.9444},
  {"company":"BEAUTY MILANO LTD","country":"IL","city":"TEL AVIV ISRAEA"},
  {"company":"BALTIKA AS","country":"EE","city":"Tallinn"},
  {"company":"TALLINK DUTY FREE AS","country":"EE","city":"TALLINN"},
  {"company":"FASHION ADDICTION S.L","country":"ES","city":"FUENLABRADA madrid","lat":40.2842,"lng":-3.7942},
  {"company":"ELEGANCE DU MARAIS","country":"FR","city":"PARIS","lat":48.8566,"lng":2.3522}
];

const THRESHOLDS = {
  contact:    { ok: 30, warn: 90 },
  repurchase: { ok: 30, warn: 90 },
  debt:       { ok: 0,  warn: 5000 },
};

const MAP_CONFIG = {
  europeGeoJSON:
    "https://cdn.jsdelivr.net/gh/leakyMirror/map-of-europe@master/GeoJSON/europe.geojson",
  regionSources: {
    IT: {
      url: "https://cdn.jsdelivr.net/gh/openpolis/geojson-italy@master/geojson/limits_IT_regions.geojson",
      nameProp: "reg_name",
    },
  },
};
